(() => {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const page = $("private-docs-page"), list = $("private-docs-list"), dialog = $("document-dialog"), form = $("document-form");
  if (!page || !list || !dialog || !form || !window.firebase?.firestore) return;
  const db = firebase.firestore(), auth = firebase.auth(), storage = firebase.storage?.(), serverTime = () => firebase.firestore.FieldValue.serverTimestamp();
  // The SDK otherwise retries some Storage failures for up to ten minutes while
  // leaving the UI at 0%. Keep retries bounded; uploadStorage also has an idle watchdog.
  storage?.setMaxUploadRetryTime?.(30000);
  storage?.setMaxOperationRetryTime?.(15000);
  const state = {user:null,tab:"personal",filter:"all",query:"",documents:[],legacy:[],commesse:[],users:[],unsubs:[],commessaOnly:"",selectedCommesse:new Set(),viewerDoc:null,saving:false,lastLoadedAt:0,referencesLoadedAt:0};
  const CACHE_TTL_MS = 5 * 60 * 1000;
  const filters = [["all","Tutti"],["pdf","PDF"],["photo","Foto"],["word","Word"],["excel","Excel"],["expiration","Con scadenza"],["expired","Scaduti"],["soon","In scadenza"],["favorite","Preferiti"],["commessa","Collegati a commessa"]];
  const allowedExtensions = new Set(["pdf","jpg","jpeg","png","webp","doc","docx","xls","xlsx","csv","txt","ppt","pptx"]);
  const MB = 1024 * 1024, rawImageLimit = 25 * MB;
  const uploadPhases = {validating:"Validazione…",optimizing:"Ottimizzazione immagine…",uploading:"Caricamento…",saving:"Salvataggio metadati…",creatingReminder:"Creazione promemoria…",completed:"Documento salvato.",failed:"Salvataggio non riuscito"};
  const esc = (v) => String(v ?? "").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const uid=()=>state.user?.uid||"", visibility=d=>d.visibility||"personal", ids=d=>Array.isArray(d.commessaIds)?d.commessaIds.filter(Boolean):(d.commessaId?[d.commessaId]:[]);
  const commessaName=id=>state.commesse.find(c=>c.id===id)?.nome||state.commesse.find(c=>c.id===id)?.name||"";
  const canEdit=d=>Boolean(uid()&&(d.ownerUserId===uid()||d.createdBy===uid()));
  const authorized=d=>visibility(d)==="personal"?d.ownerUserId===uid():visibility(d)==="global"||d.sharedToAll||(d.authorizedUserIds||d.sharedUserIds||[]).includes(uid());
  const date=v=>{const d=v?.toDate?.()||(v?new Date(`${v}T12:00:00`):null);return d&&!Number.isNaN(d.valueOf())?d.toLocaleDateString("it-IT"):"";};
  const eventRef=id=>db.collection("calendarEvents").doc(`document_${id}`);
  const extension=d=>String(d.fileExtension||d.originalFileName||d.fileName||"").split(".").pop().toLowerCase();
  function fileKind(d){const v=`${d.mimeType||d.fileType||""} ${extension(d)}`.toLowerCase();if(/pdf/.test(v))return["pdf","📕"];if(/image|jpg|jpeg|png|webp/.test(v))return["photo","🖼️"];if(/word|docx?/.test(v))return["word","📘"];if(/excel|sheet|xlsx?|csv/.test(v))return["excel","📗"];if(/ppt/.test(v))return["other","📙"];return["other","📄"];}
  function expiry(d){if(!d.expirationDate)return["",""];const n=new Date();n.setHours(0,0,0,0);const days=Math.ceil((new Date(`${d.expirationDate}T00:00:00`)-n)/86400000);return days<0?["expired","Scaduto"]:days<=7?["soon",days===0?"Scade oggi":`Scade tra ${days} giorni`]:["valid","In corso"];}
  function normalizeLegacy(d){return{...d,legacy:true,visibility:"personal",ownerUserId:uid(),commessaIds:ids(d),category:d.category||"Documento",fileUrl:d.fileUrl||d.driveWebViewLink||d.fileDataUrl||"",originalFileName:d.originalFileName||d.fileName||"",uploadStatus:d.uploadStatus||((d.fileUrl||d.driveWebViewLink||d.fileDataUrl)?"completed":"failed"),favoriteBy:d.favoriteBy||[]};}
  function visible(){const q=state.query.trim().toLowerCase();return[...state.documents,...state.legacy.map(normalizeLegacy)].filter(authorized).filter(d=>visibility(d)===state.tab&&(!state.commessaOnly||ids(d).includes(state.commessaOnly))).filter(d=>{const[k]=fileKind(d),[e]=expiry(d);if(["pdf","photo","word","excel"].includes(state.filter)&&k!==state.filter)return false;if(state.filter==="expiration"&&!d.expirationDate)return false;if(["expired","soon"].includes(state.filter)&&e!==state.filter)return false;if(state.filter==="favorite"&&!(d.favoriteBy||[]).includes(uid()))return false;if(state.filter==="commessa"&&!ids(d).length)return false;return!q||[d.name,d.category,d.description,d.originalFileName,...ids(d).map(commessaName)].some(v=>String(v||"").toLowerCase().includes(q));});}
  function commesseText(d){const linked=ids(d), names=linked.map(commessaName).filter(Boolean);if(linked.length===1)return names[0]||"1 commessa collegata";return linked.length?`${linked.length} commesse collegate`:"";}
  function render(){ $("documents-filters").innerHTML=filters.map(([id,label])=>`<button type="button" class="documents-filter ${state.filter===id?"active":""}" data-doc-filter="${id}">${label}</button>`).join("");document.querySelectorAll("[data-doc-tab]").forEach(b=>b.classList.toggle("active",b.dataset.docTab===state.tab));const rows=visible();$("private-docs-feedback").textContent=`${rows.length} ${rows.length===1?"documento":"documenti"}`;if(!rows.length){list.innerHTML=`<div class="documents-empty"><span>📂</span><strong>Nessun documento in questa scheda.</strong><button class="btn btn-primary" data-empty-new>+ Aggiungi documento</button></div>`;return;}
    list.innerHTML=rows.map(d=>{const[k,icon]=fileKind(d),[s,st]=expiry(d),fav=(d.favoriteBy||[]).includes(uid()),linked=commesseText(d);return`<article class="document-card" tabindex="0" role="button" data-document-id="${esc(d.id)}"><div class="document-format document-format-${k}">${icon}</div><div class="document-card-body"><div class="document-title-row"><h3>${esc(d.name||"Documento")}</h3><button class="document-star ${fav?"active":""}" data-doc-action="favorite" aria-label="Preferito">★</button><button class="document-menu-btn" data-doc-action="menu" aria-label="Azioni documento">⋮</button></div><p>${esc(d.category||"Senza categoria")} • ${esc(extension(d).toUpperCase()||"FILE")}</p>${linked?`<button class="document-commesse-link" data-doc-action="commesse">${esc(linked)}</button>`:""}<div class="document-meta">${d.expirationDate?`<span class="expiration-${s}">Scade il ${esc(date(d.expirationDate))} • ${st}</span>`:""}${d.uploadStatus&&d.uploadStatus!=="completed"?'<span class="expiration-expired">File non disponibile</span>':""}</div></div><div class="document-actions hidden"><button data-doc-action="open">Apri</button><button data-doc-action="download">Scarica</button>${canEdit(d)&&!d.legacy?'<button data-doc-action="edit">Modifica</button><button class="danger" data-doc-action="delete">Elimina</button>':""}</div></article>`;}).join(""); }
  function selectionSummary(){const n=state.selectedCommesse.size,text=`${n} ${n===1?"commessa selezionata":"commesse selezionate"}`;$("document-commesse-summary").textContent=text;$("document-commesse-count").textContent=text;}
  function renderCommesse(){const q=$("document-commesse-search").value.trim().toLowerCase();$("document-commesse-list").innerHTML=state.commesse.filter(c=>(c.nome||c.name||"").toLowerCase().includes(q)).map(c=>`<label><input type="checkbox" value="${esc(c.id)}" ${state.selectedCommesse.has(c.id)?"checked":""}> ${esc(c.nome||c.name||"Commessa")}</label>`).join("")||'<p class="muted">Nessuna commessa trovata.</p>';selectionSummary();}
  async function loadReferences(force=false){if(!force&&state.referencesLoadedAt&&Date.now()-state.referencesLoadedAt<CACHE_TTL_MS)return;const[c,u]=await Promise.all([db.collection("commesse").get().catch(()=>null),db.collection("utenti").get().catch(()=>null)]);state.commesse=c?.docs.map(x=>({id:x.id,...x.data()}))||[];state.users=u?.docs.map(x=>({id:x.id,...x.data()})).filter(x=>x.id!==uid())||[];state.referencesLoadedAt=Date.now();$("document-users").innerHTML=state.users.map(x=>`<label><input type="checkbox" value="${esc(x.id)}"> ${esc(x.nome||x.displayName||x.email||"Utente")}</label>`).join("");}
  function openForm(d=null){if(!state.user)return alert("Devi fare login per usare i documenti.");form.reset();$("document-id").value=d?.id||db.collection("documents").doc().id;$("document-form-title").textContent=d?"Modifica documento":"Nuovo documento";$("document-name").value=d?.name||"";$("document-category").value=d?.category||"";$("document-description").value=d?.description||"";$("document-expiration").value=d?.expirationDate||"";state.selectedCommesse=new Set(d?ids(d):(state.commessaOnly?[state.commessaOnly]:[]));selectionSummary();const vis=d?.visibility||state.tab||"personal";form.querySelector(`[name=document-visibility][value=${vis}]`).checked=true;$("document-recipients").classList.toggle("hidden",vis!=="shared");$("document-share-all").checked=Boolean(d?.sharedToAll);form.querySelectorAll("#document-users input").forEach(i=>i.checked=(d?.sharedUserIds||[]).includes(i.value));$("document-favorite").checked=(d?.favoriteBy||[]).includes(uid());$("document-file-preview").textContent=d?.originalFileName||d?.fileName||"Nessun file selezionato.";$("document-form-feedback").textContent="";dialog.showModal?.();}
  function fileLimit(file){
    const ext=String(file?.name||"").split(".").pop().toLowerCase();
    if(String(file?.type||"").startsWith("image/")||["jpg","jpeg","png","webp"].includes(ext))return 5*MB;
    if(ext==="pdf"||file?.type==="application/pdf")return 15*MB;
    return 10*MB;
  }
  function formatBytes(bytes){if(!Number.isFinite(bytes))return "—";return bytes>=MB?`${(bytes/MB).toFixed(2)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`;}
  function documentError(code,message){const error=new Error(message);error.code=code;return error;}
  function validateFile(file,{afterOptimization=false}={}){
    if(!file)return;
    const ext=String(file.name||"").split(".").pop().toLowerCase();
    if(!allowedExtensions.has(ext))throw documentError("document/unsupported-format","Formato file non supportato.");
    const limit=fileLimit(file), image=String(file.type||"").startsWith("image/")||["jpg","jpeg","png","webp"].includes(ext);
    if(file.size>(image&&!afterOptimization?rawImageLimit:limit))throw documentError("document/file-too-large",`Il file è troppo grande. Dimensione massima consentita: ${formatBytes(limit)}.`);
    if(!file.size)throw documentError("document/empty-file","Il file selezionato è vuoto.");
  }
  function sanitizeFileName(name,documentId,mimeType=""){
    const raw=String(name||"file").normalize("NFKD").replace(/[\/\\\x00-\x1f\x7f]+/g,"_").replace(/\.{2,}/g,".");
    let ext=raw.includes(".")?raw.split(".").pop().toLowerCase().replace(/[^a-z0-9]/g,""):"";
    if(!ext&&mimeType.includes("jpeg"))ext="jpg";else if(!ext&&mimeType.includes("png"))ext="png";else if(!ext&&mimeType.includes("webp"))ext="webp";
    const base=raw.replace(/\.[^.]*$/,"").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/^[-.]+|[-.]+$/g,"").slice(0,80)||"file";
    return `${base}-${documentId.slice(-8)}${ext?`.${ext}`:""}`;
  }
  function stripUndefined(value){
    if(Array.isArray(value))return value.filter(v=>v!==undefined).map(stripUndefined);
    if(value&&Object.getPrototypeOf(value)===Object.prototype)return Object.fromEntries(Object.entries(value).filter(([,v])=>v!==undefined).map(([k,v])=>[k,stripUndefined(v)]));
    return value;
  }
  async function sha256(file){if(!crypto?.subtle)return "";const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("");}
  async function canvasBlob(canvas,type,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(documentError("document/optimization-failed","Impossibile ottimizzare l’immagine.")),type,quality));}
  async function optimizeImage(file,maxWidth=1920,quality=.8){
    if(!String(file.type||"").startsWith("image/"))return file;
    const bitmap=await createImageBitmap(file,{imageOrientation:"from-image"});
    const scale=Math.min(1,maxWidth/bitmap.width),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
    canvas.getContext("2d",{alpha:false}).drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();
    const type=file.type==="image/png"&&file.size<2*MB?"image/png":"image/jpeg",blob=await canvasBlob(canvas,type,type==="image/png"?undefined:quality);
    if(blob.size>=file.size)return file;
    return new File([blob],String(file.name||"foto").replace(/\.[^.]+$/,type==="image/png"?".png":".jpg"),{type,lastModified:file.lastModified});
  }
  async function makeThumbnail(file){
    if(!String(file.type||"").startsWith("image/"))return null;
    const bitmap=await createImageBitmap(file),scale=Math.min(1,320/bitmap.width),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return canvasBlob(canvas,"image/jpeg",.62);
  }
  function setSavePhase(phase,progress){
    const button=$("document-save"),feedback=$("document-form-feedback");button.textContent=phase==="idle"?"Salva documento":phase==="failed"?"Riprova":"Salvataggio…";
    feedback.className=`document-save-feedback ${phase}`;feedback.innerHTML=phase==="failed"?feedback.innerHTML:`<strong>${esc(uploadPhases[phase]||"")}</strong>${Number.isFinite(progress)?`<span>${Math.round(progress)}%</span><progress max="100" value="${Math.round(progress)}"></progress>`:""}`;
  }
  function getFriendlyDocumentError(error){
    const code=String(error?.code||"").toLowerCase(),message=String(error?.message||"").toLowerCase();
    if(code.includes("file-too-large"))return error.message;if(code.includes("unsupported-format"))return "Formato file non supportato.";
    if(code.includes("unauth")||message.includes("sessione"))return "Sessione non valida. Accedi nuovamente e riprova.";
    if(code.includes("unauthorized")||code.includes("permission-denied"))return "Non hai il permesso di caricare questo documento.";
    if(code.includes("quota-exceeded")||code.includes("resource-exhausted"))return "Lo spazio disponibile non è sufficiente oppure il servizio non è momentaneamente disponibile.";
    if(code.includes("bucket-not-found")||code.includes("project-not-found")||code.includes("storage/unavailable"))return "L’archivio documenti non è disponibile. Contatta l’amministratore.";
    if(code.includes("retry-limit")||code.includes("upload-timeout")||code.includes("network")||message.includes("offline"))return "Il caricamento non risponde. Controlla la connessione e riprova.";
    if(code.includes("invalid-argument")||code.includes("empty-file"))return "Alcuni dati del documento non sono validi.";
    return "Si è verificato un errore durante il salvataggio del documento. Riprova.";
  }
  function showSaveError(error){const message=getFriendlyDocumentError(error);setSavePhase("failed");$("document-form-feedback").innerHTML=`<div class="document-save-error"><strong>⚠️ Salvataggio non riuscito</strong><span>${esc(message)}</span><div><button type="submit" class="btn btn-primary">Riprova</button><button type="button" class="btn" data-dismiss-save-error>Chiudi</button></div></div>`;}
  async function uploadStorage(file,ownerUserId,documentId,onProgress){
    if(!storage)throw documentError("storage/unavailable","Firebase Storage non è disponibile.");
    const storedFileName=sanitizeFileName(file.name,documentId,file.type),storagePath=`documents/${ownerUserId}/${documentId}/${storedFileName}`,reference=storage.ref(storagePath);
    const task=reference.put(file,{contentType:file.type||"application/octet-stream",customMetadata:{documentId,ownerUserId}});
    await new Promise((resolve,reject)=>{
      let settled=false,lastBytes=-1,timer;
      const finish=callback=>value=>{if(settled)return;settled=true;clearTimeout(timer);callback(value);};
      const fail=finish(reject),done=finish(resolve);
      const armWatchdog=()=>{clearTimeout(timer);timer=setTimeout(()=>{task.cancel();fail(documentError("storage/upload-timeout","Firebase Storage non ha avviato il trasferimento entro il tempo previsto."));},30000);};
      armWatchdog();
      task.on("state_changed",snap=>{if(snap.bytesTransferred!==lastBytes){lastBytes=snap.bytesTransferred;armWatchdog();}onProgress?.(snap.totalBytes?snap.bytesTransferred/snap.totalBytes*100:0);},fail,done);
    });
    let fileUrl;
    try{fileUrl=await reference.getDownloadURL();}catch(error){await reference.delete().catch(()=>{});throw error;}
    if(!fileUrl){await reference.delete().catch(()=>{});throw documentError("storage/object-not-found","File caricato ma non disponibile.");}
    return {fileUrl,storagePath,storedFileName,reference};
  }
  async function removeStoragePath(path){if(path&&storage&&String(path).startsWith("documents/"))await storage.ref(path).delete();}
  function previewFile(file){try{validateFile(file);const[,icon]=fileKind({fileName:file.name,fileType:file.type});$("document-file-preview").innerHTML=`<span>${icon}</span><strong>${esc(file.name)}</strong><span>${esc(file.name.split(".").pop().toUpperCase())} • ${formatBytes(file.size)}</span><span>Le immagini saranno ottimizzate prima del caricamento.</span><button class="btn" type="button" data-remove-file>Rimuovi o cambia file</button>`;setSavePhase("idle");}catch(e){$("document-file-preview").textContent="Nessun file selezionato.";showSaveError(e);$("document-file").value="";$("document-camera").value="";}}
  function normalizeUrl(d){let value=d.fileUrl||d.downloadUrl||d.driveWebViewLink||d.fileDataUrl||"";if(value&&typeof value==="object")value=value.url||value.href||"";value=String(value).trim();if(value.startsWith("{")&&value.endsWith("}")){try{const parsed=JSON.parse(value);value=String(parsed.url||parsed.fileUrl||parsed.webViewLink||"");}catch(e){console.error("Invalid document URL payload",e);return"";}}return /^(https?:|data:|blob:)/i.test(value)&&value!=="about:blank"?value:"";}
  function fileName(d){const ext=extension(d),base=String(d.originalFileName||d.name||"documento").replace(/\.[^.]+$/,"").replace(/[^a-z0-9._-]+/gi,"_");return `${base||"documento"}${ext?`.${ext}`:""}`;}
  function showOpenError(d,error){console.error("Document open failed",{documentId:d?.id,error});state.viewerDoc=d;$("document-error-dialog").showModal?.();}
  async function download(d){const url=normalizeUrl(d);if(!url||d.uploadStatus&&d.uploadStatus!=="completed")throw new Error("URL non disponibile");const a=document.createElement("a");a.href=url;a.download=fileName(d);a.rel="noopener";document.body.appendChild(a);a.click();a.remove();}
  function openViewer(d){const url=normalizeUrl(d);if(!url||d.uploadStatus&&d.uploadStatus!=="completed")return showOpenError(d,"missing or incomplete file");state.viewerDoc=d;const[k]=fileKind(d),viewer=$("document-viewer"),content=$("document-viewer-content");$("document-viewer-title").textContent=d.name||"Documento";$("document-viewer-page").textContent=k==="pdf"?"PDF":"";content.innerHTML='<p>Caricamento documento…</p>';viewer.showModal?.();setTimeout(()=>{if(k==="photo")content.innerHTML=`<img src="${esc(url)}" alt="${esc(d.name||"Documento")}" data-document-media>`;else if(k==="pdf")content.innerHTML=`<object data="${esc(url)}" type="application/pdf"><div class="document-generic"><p>Anteprima PDF non disponibile.</p><button class="btn btn-primary" data-viewer-download>Scarica</button></div></object>`;else content.innerHTML=`<div class="document-generic"><div class="document-format">${fileKind(d)[1]}</div><h2>${esc(d.name||"Documento")}</h2><p>${esc(extension(d).toUpperCase())} • ${d.fileSize?`${(d.fileSize/1024/1024).toFixed(2)} MB`:"Dimensione non disponibile"}</p><button class="btn btn-primary" data-viewer-download>Scarica</button><button class="btn" data-viewer-external>Apri con un'altra applicazione</button></div>`;},30);}
  async function syncExpiration(id,data,old={}){const ref=eventRef(id);if(!data.expirationDate){if(old.calendarEventId)await ref.delete().catch(()=>{});return"";}const names=data.commessaIds.map(commessaName).filter(Boolean);await ref.set({type:"SCADENZA_DOCUMENTO",title:`Scadenza documento – ${data.name}`,startDate:data.expirationDate,endDate:data.expirationDate,allDay:true,documentId:id,documentVisibility:data.visibility,ownerUserId:data.ownerUserId,authorizedUserIds:data.visibility==="personal"?[data.ownerUserId]:data.sharedUserIds,sharedToAll:Boolean(data.sharedToAll),commessaIds:data.commessaIds,worksite:`Commesse collegate: ${data.commessaIds.length}`,description:`Commesse collegate: ${data.commessaIds.length}${names.length?`\n${names.join(", ")}`:""}`,createdByUid:data.createdBy||uid(),reminderDate:data.reminderDate,reminderDaysBefore:7,updatedAt:serverTime()},{merge:true});return ref.id;}
  form.addEventListener("submit",async e=>{
    e.preventDefault();if(state.saving)return;state.saving=true;const button=$("document-save");button.disabled=true;
    let uploaded=null,thumbnailUpload=null,metadataSaved=false;
    try{
      setSavePhase("validating");const user=auth.currentUser;if(!user?.uid||!state.user?.uid)throw documentError("unauthenticated","Sessione non valida");
      const id=$("document-id").value||db.collection("documents").doc().id,ref=db.collection("documents").doc(id),old=state.documents.find(x=>x.id===id)||{},sourceFile=$("document-file").files[0]||$("document-camera").files[0],vis=form.querySelector("[name=document-visibility]:checked")?.value;
      if(!["personal","shared","global"].includes(vis))throw documentError("invalid-argument","Visibilità non valida");
      const shared=[...form.querySelectorAll("#document-users input:checked")].map(x=>x.value).filter(Boolean),all=$("document-share-all").checked;
      if(vis==="shared"&&!all&&!shared.length)throw documentError("invalid-argument","Seleziona almeno un destinatario");if(!sourceFile&&!normalizeUrl(old))throw documentError("invalid-argument","Seleziona un file");
      let file=sourceFile,fileHash=old.fileHash||"",thumbnailPath=old.thumbnailPath||"",thumbnailUrl=old.thumbnailUrl||"";
      if(file){validateFile(file);fileHash=await sha256(file);if(fileHash){const duplicate=await db.collection("documents").where("ownerUserId","==",user.uid).where("fileHash","==",fileHash).limit(1).get();if(!duplicate.empty&&!confirm("Questo file risulta già presente. Premere OK per caricarne comunque una nuova copia, oppure Annulla per usare il documento esistente.")){openViewer({id:duplicate.docs[0].id,...duplicate.docs[0].data()});throw documentError("document/duplicate","Caricamento annullato: il file è già presente.");}}
        setSavePhase("optimizing");file=await optimizeImage(file);validateFile(file,{afterOptimization:true});uploaded=await uploadStorage(file,user.uid,id,p=>setSavePhase("uploading",p));
        const thumbnail=await makeThumbnail(file).catch(error=>{console.warn("Document thumbnail failed",{documentId:id,code:error?.code,message:error?.message});return null;});if(thumbnail){thumbnailUpload=await uploadStorage(new File([thumbnail],"thumbnail.jpg",{type:"image/jpeg"}),user.uid,id);thumbnailPath=thumbnailUpload.storagePath;thumbnailUrl=thumbnailUpload.fileUrl;}
      }
      const expiration=$("document-expiration").value||null;if(expiration&&!/^\d{4}-\d{2}-\d{2}$/.test(expiration))throw documentError("invalid-argument","Data non valida");const reminder=expiration?new Date(`${expiration}T12:00:00Z`).getTime()-7*86400000:null;
      setSavePhase("saving");const normalizedCommessaIds=[...state.selectedCommesse].filter(Boolean),data=stripUndefined({id,name:$("document-name").value.trim(),category:$("document-category").value.trim(),description:$("document-description").value.trim(),visibility:vis,ownerUserId:old.ownerUserId||user.uid,sharedUserIds:vis==="shared"?shared:[],sharedTeamIds:Array.isArray(old.sharedTeamIds)?old.sharedTeamIds:[],sharedToAll:vis!=="personal"&&(vis==="global"||all),authorizedUserIds:vis==="personal"?[user.uid]:shared,commessaIds:normalizedCommessaIds,expirationDate:expiration,reminderDate:reminder?new Date(reminder).toISOString().slice(0,10):null,reminderDaysBefore:7,reminderEnabled:Boolean(expiration),favoriteBy:$("document-favorite").checked?[...new Set([...(old.favoriteBy||[]),user.uid])]:(old.favoriteBy||[]).filter(x=>x!==user.uid),originalFileName:sourceFile?.name||old.originalFileName||old.fileName||"",storedFileName:uploaded?.storedFileName||old.storedFileName||"",fileExtension:String(file?.name||old.originalFileName||"").split(".").pop().toLowerCase(),mimeType:file?.type||old.mimeType||old.fileType||"application/octet-stream",fileSize:file?.size||old.fileSize||0,originalFileSize:sourceFile?.size||old.originalFileSize||old.fileSize||0,fileHash,fileUrl:uploaded?.fileUrl||old.fileUrl||"",storagePath:uploaded?.storagePath||old.storagePath||(old.fileId?`drive:${old.fileId}`:old.fileUrl?`legacy:${id}`:""),thumbnailPath,thumbnailUrl,createdBy:old.createdBy||user.uid,updatedBy:user.uid,createdAt:old.createdAt||serverTime(),updatedAt:serverTime(),uploadStatus:"completed",versionHistoryEnabled:false,status:"active"});
      if(!data.name||!data.id||!data.ownerUserId||!data.fileUrl||!data.storagePath||!data.fileSize||!data.mimeType)throw documentError("invalid-argument","Metadati incompleti");await ref.set(data,{merge:true});metadataSaved=true;const savedIndex=state.documents.findIndex(item=>item.id===id);const savedDocument={...old,...data,id};if(savedIndex>=0)state.documents[savedIndex]=savedDocument;else state.documents.push(savedDocument);render();
      setSavePhase("creatingReminder");try{data.calendarEventId=await syncExpiration(id,data,old);if(data.calendarEventId)await ref.update({calendarEventId:data.calendarEventId});}catch(error){console.error("Document secondary operation failed",{operation:"syncExpiration",documentId:id,userId:user.uid,code:error?.code,message:error?.message,stack:error?.stack});alert("Documento salvato correttamente. Non è stato possibile creare il promemoria della scadenza.");}
      if(sourceFile&&old.storagePath&&old.storagePath!==data.storagePath)await removeStoragePath(old.storagePath).catch(error=>console.warn("Old document cleanup failed",error));if(sourceFile&&old.thumbnailPath&&old.thumbnailPath!==data.thumbnailPath)await removeStoragePath(old.thumbnailPath).catch(()=>{});
      setSavePhase("completed");dialog.close();
    }catch(error){
      console.error("Document save failed",{operation:"saveDocument",phase:$("document-form-feedback")?.textContent,documentId:$("document-id").value,userId:auth.currentUser?.uid||null,ownerUserId:auth.currentUser?.uid||null,storagePath:uploaded?.storagePath||null,originalFileName:($("document-file").files[0]||$("document-camera").files[0])?.name||null,mimeType:($("document-file").files[0]||$("document-camera").files[0])?.type||null,fileSize:($("document-file").files[0]||$("document-camera").files[0])?.size||null,visibility:form.querySelector("[name=document-visibility]:checked")?.value,commessaIds:[...state.selectedCommesse],expirationDate:$("document-expiration").value||null,platform:window.Capacitor?.getPlatform?.()||"web",code:error?.code,message:error?.message,stack:error?.stack});
      if(!metadataSaved){await Promise.allSettled([removeStoragePath(uploaded?.storagePath),removeStoragePath(thumbnailUpload?.storagePath)]);}showSaveError(error);
    }finally{state.saving=false;button.disabled=false;}
  });
  async function act(card,action){const d=[...state.documents,...state.legacy.map(normalizeLegacy)].find(x=>x.id===card.dataset.documentId);if(!d)return;document.querySelectorAll(".document-actions").forEach(m=>{if(m!==card.querySelector(".document-actions"))m.classList.add("hidden")});if(action==="menu")return card.querySelector(".document-actions").classList.toggle("hidden");card.querySelector(".document-actions")?.classList.add("hidden");if(action==="open")return openViewer(d);if(action==="download")return download(d).catch(e=>{console.error(e);alert("Download non riuscito. Controlla la connessione e riprova.");});if(action==="edit")return openForm(d);if(action==="commesse")return alert(ids(d).map(commessaName).filter(Boolean).join("\n")||"Nessuna commessa visibile.");if(action==="favorite"&&!d.legacy)return db.collection("documents").doc(d.id).update({favoriteBy:(d.favoriteBy||[]).includes(uid())?firebase.firestore.FieldValue.arrayRemove(uid()):firebase.firestore.FieldValue.arrayUnion(uid()),updatedAt:serverTime()});if(action==="delete"&&confirm(`Vuoi eliminare definitivamente il documento ‘${d.name}’?`)){await eventRef(d.id).delete().catch(()=>{});await db.collection("documentReminderAcknowledgements").where("documentId","==",d.id).get().then(s=>Promise.all(s.docs.map(x=>x.ref.delete()))).catch(()=>{});await db.collection("documents").doc(d.id).delete();const samePath=d.storagePath?await db.collection("documents").where("storagePath","==",d.storagePath).limit(1).get():null;if(!samePath||samePath.empty)await removeStoragePath(d.storagePath).catch(error=>console.warn("Document file cleanup failed",error));await removeStoragePath(d.thumbnailPath).catch(()=>{});}}
  page.addEventListener("click",e=>{if(e.target.closest("[data-dismiss-save-error]")){setSavePhase("idle");return;}const tab=e.target.closest("[data-doc-tab]");if(tab){state.tab=tab.dataset.docTab;state.commessaOnly="";render();return;}const fil=e.target.closest("[data-doc-filter]");if(fil){state.filter=fil.dataset.docFilter;render();return;}if(e.target.closest("[data-empty-new]"))return openForm();const action=e.target.closest("[data-doc-action]");if(action){e.stopPropagation();return act(action.closest(".document-card"),action.dataset.docAction);}const card=e.target.closest(".document-card");if(card)act(card,"open");});
  page.addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target.classList.contains("document-card")){e.preventDefault();act(e.target,"open");}});document.addEventListener("click",e=>{if(!e.target.closest(".document-card"))document.querySelectorAll(".document-actions").forEach(x=>x.classList.add("hidden"));});
  $("document-file").addEventListener("change",e=>previewFile(e.target.files[0]));$("document-camera").addEventListener("change",e=>previewFile(e.target.files[0]));$("document-file-preview").addEventListener("click",e=>{if(e.target.closest("[data-remove-file]")){$("document-file").value="";$("document-camera").value="";$("document-file-preview").textContent="Nessun file selezionato.";}});$("document-commesse-open").onclick=()=>{renderCommesse();$("document-commesse-dialog").showModal?.();};$("document-commesse-search").oninput=renderCommesse;$("document-commesse-list").onchange=e=>{e.target.checked?state.selectedCommesse.add(e.target.value):state.selectedCommesse.delete(e.target.value);selectionSummary();};$("document-commesse-all").onclick=()=>{state.commesse.forEach(c=>state.selectedCommesse.add(c.id));renderCommesse();};$("document-commesse-none").onclick=()=>{state.selectedCommesse.clear();renderCommesse();};$("document-commesse-confirm").onclick=selectionSummary;
  $("document-viewer-back").onclick=()=>$("document-viewer").close();$("document-viewer-download").onclick=()=>download(state.viewerDoc).catch(()=>alert("Download non riuscito. Controlla la connessione e riprova."));$("document-viewer-external").onclick=()=>{const u=normalizeUrl(state.viewerDoc);if(u)window.open(u,"_blank","noopener,noreferrer");else showOpenError(state.viewerDoc,"invalid URL");};$("document-viewer-content").onclick=e=>{if(e.target.closest("[data-viewer-download]"))download(state.viewerDoc);if(e.target.closest("[data-viewer-external]"))$("document-viewer-external").click();};let zoom=1;const setZoom=n=>{zoom=Math.max(.5,Math.min(3,n));const media=$("document-viewer-content").querySelector("img,object");if(media)media.style.transform=`scale(${zoom})`;};$("document-viewer-zoom-in").onclick=()=>setZoom(zoom+.25);$("document-viewer-zoom-out").onclick=()=>setZoom(zoom-.25);$("document-error-close").onclick=()=>$("document-error-dialog").close();$("document-error-retry").onclick=()=>{$("document-error-dialog").close();openViewer(state.viewerDoc);};
  $("documents-search").oninput=e=>{state.query=e.target.value;render();};$("documents-new-btn").onclick=()=>openForm();$("document-dialog-close").onclick=()=>dialog.close();$("document-cancel").onclick=()=>dialog.close();form.addEventListener("change",e=>{if(e.target.name==="document-visibility")$("document-recipients").classList.toggle("hidden",e.target.value!=="shared");});$("open-private-docs-upload-btn")?.addEventListener("click",()=>setTimeout(()=>openForm(),80));$("commessa-documents-btn")?.addEventListener("click",()=>{const m=location.hash.match(/commessa=([^&]+)/);state.commessaOnly=m?decodeURIComponent(m[1]):"";state.tab="global";$("open-private-docs-btn")?.click();setTimeout(render,60);});
  function deactivate(){state.unsubs.splice(0).forEach(f=>f());}
  function activate(force=false){const user=state.user;if(!user)return render();if(!force&&state.lastLoadedAt&&Date.now()-state.lastLoadedAt<CACHE_TTL_MS){render();return;}deactivate();const merge=new Map(state.documents.map(d=>[d.id,d])),watch=q=>state.unsubs.push(q.onSnapshot(s=>{s.docChanges().forEach(c=>c.type==="removed"?merge.delete(c.doc.id):merge.set(c.doc.id,{id:c.doc.id,...c.doc.data()}));state.documents=[...merge.values()];render();},e=>console.error("Document query failed",e)));watch(db.collection("documents").where("ownerUserId","==",user.uid));watch(db.collection("documents").where("visibility","==","shared").where("sharedUserIds","array-contains",user.uid));watch(db.collection("documents").where("visibility","==","shared").where("sharedToAll","==",true));watch(db.collection("documents").where("visibility","==","global"));state.unsubs.push(db.collection("privateDocuments").doc(user.uid).collection("items").onSnapshot(s=>{state.legacy=s.docs.map(x=>({id:x.id,...x.data()}));render();}));state.lastLoadedAt=Date.now();loadReferences().then(render);}
  function subscribe(user){deactivate();state.user=user;state.lastLoadedAt=0;if(!user){state.documents=[];state.legacy=[];return render();}if(!page.classList.contains("hidden"))activate();else render();}
  const online=()=>$("documents-offline").classList.toggle("hidden",navigator.onLine);window.addEventListener("online",online);window.addEventListener("offline",online);window.addEventListener("hashchange",()=>page.classList.contains("hidden")?deactivate():activate());online();render();auth.onAuthStateChanged(subscribe);window.HeraDocuments={getFriendlyDocumentError,sanitizeFileName,stripUndefined,activate,deactivate,open:(o={})=>{state.commessaOnly=o.commessaId||"";state.tab=o.visibility||"global";$("open-private-docs-btn")?.click();activate();setTimeout(()=>o.create?openForm():render(),50);}};
})();
