(function () {
  "use strict";
  const core = globalThis.HeraManagementCore;
  if (!core) return;
  const state = { personnelFilter: "Tutti", vehicleFilter: "Tutti", personnelQuery: "", vehicleQuery: "", preview: null };
  const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const isManager = () => typeof canManageData === "function" && canManageData();
  const commesse = () => Array.from(commesseById?.entries?.() || []).map(([id, value]) => ({ id, ...value }));
  const resolveCommessa = (value) => { const target = core.key(value); return commesse().find((c) => [c.id,c.codice,c.nome].some((v) => core.key(v) === target))?.id || ""; };
  const enabledIds = (person) => core.legacyEnabledIds(person, resolveCommessa);
  const displayPerson = (p) => typeof getPersonaleDisplayName === "function" ? getPersonaleDisplayName(p) : `${p.cognome || ""} ${p.nome || ""}`.trim();
  const statusClass = (status) => /attivo|disponibile/i.test(status) ? "ok" : /assente|ferie|malattia|permesso|riposo|manutenzione|assegnato|in uso/i.test(status) ? "warn" : /sospeso|cessato|guasto|fuori servizio|dismesso/i.test(status) ? "bad" : "";
  const modal = () => { let el=document.getElementById("registry-modal"); if(!el){el=document.createElement("div");el.id="registry-modal";el.className="registry-modal hidden";el.innerHTML='<div class="registry-dialog" role="dialog" aria-modal="true"></div>';document.body.appendChild(el);el.addEventListener("click",e=>{if(e.target===el)closeModal();});} return el; };
  const closeModal = () => { modal().classList.add("hidden"); modal().querySelector(".registry-dialog").innerHTML=""; state.preview=null; };
  const openModal = (html) => { const el=modal();el.querySelector(".registry-dialog").innerHTML=html;el.classList.remove("hidden");el.querySelector(".registry-close")?.addEventListener("click",closeModal); };
  const managerActions = (type) => isManager() ? `<button class="btn btn-primary" data-new="${type}">+ Nuovo ${type === "personale" ? "operatore" : "mezzo"}</button><button class="btn" data-import="${type}">Importa matrice</button><button class="btn" data-template="${type}">Scarica matrice</button><button class="btn" data-export="${type}">Esporta elenco</button><button class="btn" data-undo="${type}">Annulla ultima importazione</button>` : "";

  function enhancePanels() {
    const pp=document.getElementById("panel-personale"), vp=document.getElementById("panel-mezzi");
    if(pp&&!pp.dataset.v2){pp.dataset.v2="1";pp.innerHTML='<div id="personnel-v2" class="registry-v2"></div>';}
    if(vp&&!vp.dataset.v2){vp.dataset.v2="1";vp.innerHTML='<div id="vehicles-v2" class="registry-v2"></div>';}
    renderPersonnel();renderVehicles();
  }
  function statsMarkup(values){return `<div class="registry-summary">${values.map(([n,v])=>`<div class="registry-stat"><strong>${v}</strong><small>${esc(n)}</small></div>`).join("")}</div>`;}
  function bindToolbar(root,type){
    root.querySelector("[data-search]")?.addEventListener("input",e=>{state[type==="personale"?"personnelQuery":"vehicleQuery"]=e.target.value;type==="personale"?renderPersonnel():renderVehicles();});
    root.querySelector("[data-filter]")?.addEventListener("change",e=>{state[type==="personale"?"personnelFilter":"vehicleFilter"]=e.target.value;type==="personale"?renderPersonnel():renderVehicles();});
    root.querySelector("[data-new]")?.addEventListener("click",()=>openEditor(type));
    root.querySelector("[data-template]")?.addEventListener("click",()=>downloadWorkbook(type,[]));
    root.querySelector("[data-export]")?.addEventListener("click",()=>downloadWorkbook(type,type==="personale"?personaleRecords:mezziRecords));
    root.querySelector("[data-import]")?.addEventListener("click",()=>chooseImport(type));
    root.querySelector("[data-undo]")?.addEventListener("click",()=>undoLastImport(type));
  }
  function renderPersonnel(){
    const root=document.getElementById("personnel-v2");if(!root||typeof personaleRecords==="undefined")return;
    const all=personaleRecords||[], q=core.key(state.personnelQuery), filter=state.personnelFilter;
    const rows=all.filter(p=>{const ids=enabledIds(p), text=core.key([displayPerson(p),p.codiceOperatore,p.email,p.telefono,p.mansione,p.stato].join(" "));return(!q||text.includes(q))&&(filter==="Tutti"||(filter==="Abilitati"?ids.length>0:filter==="Non abilitati"?ids.length===0:core.key(p.stato||"Attivo")===core.key(filter)));});
    const active=all.filter(p=>core.key(p.stato||"Attivo")==="ATTIVO").length, absent=all.filter(p=>["ASSENTE","FERIE","MALATTIA","PERMESSO","INFORTUNIO"].includes(core.key(p.stato))).length;
    root.innerHTML=`<div class="registry-head"><div><h2>PERSONALE</h2><small>${rows.length} risultati</small></div><div class="registry-actions">${managerActions("personale")}</div></div>${statsMarkup([["Totale operatori",all.length],["Attivi",active],["Assenti oggi",absent],["Abilitati",all.filter(p=>enabledIds(p).length).length],["Non abilitati",all.filter(p=>!enabledIds(p).length).length]])}<div class="registry-filterbar"><input data-search type="search" value="${esc(state.personnelQuery)}" placeholder="Cerca nome, codice, email, ruolo…"><select data-filter>${["Tutti","Attivo","Assente","Ferie","Malattia","Non disponibile","Cessato","Abilitati","Non abilitati"].map(v=>`<option ${v===filter?"selected":""}>${v}</option>`).join("")}</select></div><div class="registry-grid">${rows.map(personCard).join("")||'<p class="muted">Nessun operatore corrisponde ai filtri.</p>'}</div>`;
    bindToolbar(root,"personale");root.querySelectorAll("[data-enabled]").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();openEnabled(b.dataset.enabled);}));root.querySelectorAll("[data-person]").forEach(c=>c.addEventListener("click",()=>openEditor("personale",c.dataset.person)));
  }
  function personCard(p){const name=displayPerson(p)||"Senza nome",ids=enabledIds(p),status=p.stato||"Attivo",initials=name.split(" ").slice(0,2).map(v=>v[0]).join("").toUpperCase();return `<article class="registry-card" data-person="${esc(p.id)}"><button class="registry-more" aria-label="Azioni">⋮</button><div class="registry-card-head"><span class="registry-avatar">${esc(initials)}</span><div><h3>${esc(name)}</h3><span class="status-pill ${statusClass(status)}">${esc(status)}</span></div></div><p>${esc(p.mansione||p.ruolo||"Mansione non indicata")}${p.telefono?` • ${esc(p.telefono)}`:""}</p><p>${esc(p.squadra||"Nessuna squadra")} • ${esc(p.commessaOggi||"Nessuna commessa oggi")}</p><button class="registry-link" data-enabled="${esc(p.id)}">Commesse abilitate: ${ids.length}</button></article>`;}
  function inferCategory(m){const code=String(m.codiceMezzo||m.nId||m.nome||"").toUpperCase();if(/^MA/.test(code))return"Escavatore";if(/^A/.test(code))return"Camion";if(/^T/.test(code))return"Trattore grande";if(/^R/.test(code))return"Trattore piccolo";return"Attrezzatura";}
  function renderVehicles(){const root=document.getElementById("vehicles-v2");if(!root||typeof mezziRecords==="undefined")return;const all=mezziRecords||[],q=core.key(state.vehicleQuery),filter=state.vehicleFilter;const rows=all.filter(m=>(!q||core.key([m.nId,m.codiceMezzo,m.targa,m.marca,m.modello,m.categoria,m.stato].join(" ")).includes(q))&&(filter==="Tutti"||core.key(m.stato||"Disponibile")===core.key(filter)));root.innerHTML=`<div class="registry-head"><div><h2>MEZZI</h2><small>${rows.length} risultati</small></div><div class="registry-actions">${managerActions("mezzi")}</div></div>${statsMarkup([["Totale mezzi",all.length],["Disponibili",all.filter(m=>core.key(m.stato||"Disponibile")==="DISPONIBILE").length],["In uso",all.filter(m=>core.key(m.stato)==="IN USO").length],["In manutenzione",all.filter(m=>core.key(m.stato)==="IN MANUTENZIONE").length],["Guasti",all.filter(m=>core.key(m.stato)==="GUASTO").length]])}<div class="registry-filterbar"><input data-search type="search" value="${esc(state.vehicleQuery)}" placeholder="Cerca codice, targa, marca, modello…"><select data-filter>${["Tutti",...core.VEHICLE_STATUSES].map(v=>`<option ${v===filter?"selected":""}>${v}</option>`).join("")}</select></div><div class="registry-grid">${rows.map(vehicleCard).join("")||'<p class="muted">Nessun mezzo corrisponde ai filtri.</p>'}</div>`;bindToolbar(root,"mezzi");root.querySelectorAll("[data-vehicle]").forEach(c=>c.addEventListener("click",()=>openEditor("mezzi",c.dataset.vehicle)));}
  function vehicleCard(m){const code=m.codiceMezzo||m.nId||m.nome||m.id,status=m.stato||"Disponibile";return `<article class="registry-card" data-vehicle="${esc(m.id)}"><button class="registry-more" aria-label="Azioni">⋮</button><div class="registry-card-head"><span class="registry-avatar">🚜</span><div><h3>${esc(code)}${m.marca||m.modello?` • ${esc([m.marca,m.modello].filter(Boolean).join(" "))}`:""}</h3><span class="status-pill ${statusClass(status)}">${esc(status)}</span></div></div><p>${m.targa?`Targa ${esc(m.targa)}`:"Senza targa"}</p><p>${esc(m.categoria||inferCategory(m))} • ${esc(m.squadraAssegnata||"Non assegnato")}</p><p>${m.dataRevisione?`Prossima revisione: ${esc(m.dataRevisione)}`:"Nessuna scadenza indicata"}</p></article>`;}

  function openEnabled(id){const person=personaleRecords.find(p=>p.id===id);if(!person)return;const selected=new Set(enabledIds(person));openModal(`<div class="registry-dialog-head"><h2>Commesse abilitate – ${esc(displayPerson(person))}</h2><button class="registry-close">×</button></div><input id="enabled-search" type="search" placeholder="Cerca commessa"><p><strong id="enabled-count">${selected.size} commesse abilitate</strong></p><div class="registry-check-list">${commesse().map(c=>`<label class="registry-check" data-search-text="${esc(core.key(`${c.codice} ${c.nome}`))}"><input type="checkbox" value="${esc(c.id)}" ${selected.has(c.id)?"checked":""} ${isManager()?"":"disabled"}><span><strong>${esc(c.nome||c.id)}</strong><br><small>${esc(c.codice||c.id)} • ${esc(c.stato||"Attiva")}</small></span></label>`).join("")}</div><div class="registry-dialog-actions"><button class="btn registry-close">Annulla</button>${isManager()?'<button id="enabled-save" class="btn btn-primary">Salva modifiche</button>':""}</div>`);const dialog=modal();const update=()=>dialog.querySelector("#enabled-count").textContent=`${dialog.querySelectorAll('.registry-check input:checked').length} commesse abilitate`;dialog.querySelectorAll("input[type=checkbox]").forEach(x=>x.addEventListener("change",update));dialog.querySelector("#enabled-search").addEventListener("input",e=>dialog.querySelectorAll(".registry-check").forEach(x=>x.hidden=!x.dataset.searchText.includes(core.key(e.target.value))));dialog.querySelectorAll(".registry-close").forEach(x=>x.addEventListener("click",closeModal));dialog.querySelector("#enabled-save")?.addEventListener("click",async()=>{const next=[...dialog.querySelectorAll('.registry-check input:checked')].map(x=>x.value),before=enabledIds(person);if(!window.confirm(`Confermare ${next.length} commesse abilitate? I dati storici restano invariati.`))return;const batch=db.batch(),ref=db.collection(getPersonaleCollectionName()).doc(id);batch.set(ref,{enabledCommessaIds:core.unique(next),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});[...new Set([...before,...next])].forEach(cid=>{const action=next.includes(cid)&&!before.includes(cid)?"enabled":!next.includes(cid)&&before.includes(cid)?"disabled":"";if(action){const h=db.collection("operatorCommessaHistory").doc();batch.set(h,{operatorId:id,commessaId:cid,action,changedBy:currentUser?.uid||"",changedAt:firebase.firestore.FieldValue.serverTimestamp(),reason:"modifica manuale"});}});await batch.commit();closeModal();});}

  function openEditor(type,id=""){const isPerson=type==="personale",record=(isPerson?personaleRecords:mezziRecords).find(x=>x.id===id)||{};openModal(`<div class="registry-dialog-head"><h2>${id?"Modifica":"Nuovo"} ${isPerson?"operatore":"mezzo"}</h2><button class="registry-close">×</button></div><form id="registry-editor" class="personale-fields-grid">${isPerson?`<input name="nome" required placeholder="Nome" value="${esc(record.nome)}"><input name="cognome" required placeholder="Cognome" value="${esc(record.cognome)}"><input name="codiceOperatore" placeholder="Codice operatore" value="${esc(record.codiceOperatore)}"><input name="mansione" placeholder="Mansione" value="${esc(record.mansione)}"><input name="telefono" placeholder="Telefono" value="${esc(record.telefono)}"><input name="email" type="email" placeholder="Email" value="${esc(record.email)}"><select name="stato">${core.PERSON_STATUSES.map(v=>`<option ${v===(record.stato||"Attivo")?"selected":""}>${v}</option>`).join("")}</select>`:`<input name="codiceMezzo" required placeholder="Codice mezzo" value="${esc(record.codiceMezzo||record.nId||record.nome)}"><input name="targa" placeholder="Targa" value="${esc(record.targa)}"><select name="categoria">${core.VEHICLE_CATEGORIES.map(v=>`<option ${v===(record.categoria||inferCategory(record))?"selected":""}>${v}</option>`).join("")}</select><input name="marca" placeholder="Marca" value="${esc(record.marca)}"><input name="modello" placeholder="Modello" value="${esc(record.modello)}"><select name="stato">${core.VEHICLE_STATUSES.map(v=>`<option ${v===(record.stato||"Disponibile")?"selected":""}>${v}</option>`).join("")}</select>`}<textarea name="note" placeholder="Note">${esc(record.note)}</textarea><div class="registry-dialog-actions"><button type="button" class="btn registry-close">Annulla</button><button class="btn btn-primary">Salva</button></div></form>`);modal().querySelectorAll(".registry-close").forEach(x=>x.addEventListener("click",closeModal));modal().querySelector("form").addEventListener("submit",async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(isPerson)data.fullName=`${data.cognome} ${data.nome}`.trim();else{data.nId=data.codiceMezzo;data.nome=data.codiceMezzo;}data.updatedAt=firebase.firestore.FieldValue.serverTimestamp();if(!id){data.createdAt=firebase.firestore.FieldValue.serverTimestamp();if(isPerson)data.enabledCommessaIds=[];}const collection=isPerson?getPersonaleCollectionName():getMezziCollectionName();await(id?db.collection(collection).doc(id).set(data,{merge:true}):db.collection(collection).add(data));closeModal();});}

  function workbookRows(type,records){const isPerson=type==="personale";return records.map(r=>isPerson?{ID_OPERATORE:r.id,CODICE_OPERATORE:r.codiceOperatore||"",NOME:r.nome||"",COGNOME:r.cognome||"",TELEFONO:r.telefono||"",EMAIL:r.email||"",MANSIONE:r.mansione||r.ruolo||"",STATO:r.stato||"Attivo",NOTE:r.note||"",EMAIL_ACCESSO_APP:r.email||"",COMMESSE_ABILITATE:enabledIds(r).join("; "),MODALITA_AGGIORNAMENTO_COMMESSE:"NON_MODIFICARE",MANTIENI_ABILITAZIONI_ESISTENTI:"SÌ"}:{ID_MEZZO:r.id,CODICE_MEZZO:r.codiceMezzo||r.nId||r.nome||"",TARGA:r.targa||"",CATEGORIA:r.categoria||inferCategory(r),MARCA:r.marca||"",MODELLO:r.modello||"",STATO:r.stato||"Disponibile",NOTE:r.note||"",ATTIVO:r.attivo===false?"NO":"SÌ"});}
  async function downloadWorkbook(type,records){if(!isManager())return;const isPerson=type==="personale",wb=new ExcelJS.Workbook(),columns=isPerson?core.PERSONNEL_COLUMNS:core.VEHICLE_COLUMNS,name=isPerson?"PERSONALE":"MEZZI",ws=wb.addWorksheet(name,{views:[{state:"frozen",ySplit:1}]});ws.columns=columns.map(c=>({header:c,key:c,width:Math.min(28,Math.max(14,c.length+2)),style:{numFmt:"@"}}));workbookRows(type,records).forEach(r=>ws.addRow(r));ws.autoFilter={from:"A1",to:`${ws.getColumn(columns.length).letter}${Math.max(2,ws.rowCount)}`};ws.getRow(1).eachCell(c=>{c.font={bold:true,color:{argb:"FFFFFFFF"}};c.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF1769AA"}};c.alignment={wrapText:true};});[3,4,isPerson?20:2].forEach(i=>ws.getColumn(i).eachCell((c,row)=>{if(row>1)c.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFFFF2CC"}};}));const instructions=wb.addWorksheet("ISTRUZIONI");instructions.addRows([["ISTRUZIONI"],["Compilare le colonne tramite intestazione. Date: GG/MM/AAAA."],["Le celle vuote non cancellano dati esistenti."],["Le commesse multiple sono separate da punto e virgola."],["L'importazione mostra sempre un'anteprima prima del salvataggio."],["Per le abilitazioni il valore predefinito è NON_MODIFICARE e MANTIENI=SÌ."]]);const allowed=wb.addWorksheet("VALORI_AMMESSI");const lists=isPerson?[["STATO",...core.PERSON_STATUSES],["RUOLO_APP","admin","responsabile","operatore","visualizzatore"],["MODALITA_AGGIORNAMENTO_COMMESSE",...core.MODES],["SÌ/NO","SÌ","NO"]]:[["CATEGORIA",...core.VEHICLE_CATEGORIES],["STATO",...core.VEHICLE_STATUSES],["ALIMENTAZIONE","Diesel","Benzina","Elettrico","Ibrido","GPL","Metano","Altro"]];lists.forEach((list,i)=>list.forEach((v,j)=>allowed.getCell(j+1,i+1).value=v));const teams=wb.addWorksheet("SQUADRE_DISPONIBILI");teams.addRow(["NOME"]);const available=wb.addWorksheet("COMMESSE_DISPONIBILI");available.addRow(["ID","CODICE","NOME","STATO"]);commesse().forEach(c=>available.addRow([c.id,c.codice||"",c.nome||"",c.stato||"Attiva"]));if(!isPerson){const people=wb.addWorksheet("PERSONALE_DISPONIBILE");people.addRow(["ID","NOME"]);personaleRecords.filter(p=>core.key(p.stato||"Attivo")==="ATTIVO").forEach(p=>people.addRow([p.id,displayPerson(p)]));}wb.worksheets.slice(1).forEach(s=>{s.getRow(1).font={bold:true};s.protect("hera-support",{selectLockedCells:true});});const blob=new Blob([await wb.xlsx.writeBuffer()],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=isPerson?"Matrice_Personale.xlsx":"Matrice_Mezzi.xlsx";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  async function undoLastImport(type){if(!isManager())return;const snap=await db.collection("registryImportBackups").where("registry","==",type).orderBy("createdAt","desc").limit(1).get();if(snap.empty){alert("Nessuna importazione annullabile trovata.");return;}const backup=snap.docs[0],data=backup.data(),previous=Array.isArray(data.previous)?data.previous:[];if(!previous.length){alert("Il backup non contiene record precedenti ripristinabili.");return;}if(!window.confirm(`Ripristinare ${previous.length} record modificati dall’ultima importazione? I record nuovi non vengono eliminati automaticamente.`))return;const collection=type==="personale"?getPersonaleCollectionName():getMezziCollectionName(),batch=db.batch();previous.forEach(item=>batch.set(db.collection(collection).doc(item.id),item.data,{merge:false}));batch.delete(backup.ref);await batch.commit();alert(`Ripristinati ${previous.length} record. I dati storici sono rimasti invariati.`);}
  function chooseImport(type){const input=document.createElement("input");input.type="file";input.accept=".xlsx,.xls,.csv";input.onchange=()=>previewImport(type,input.files[0]);input.click();}
  async function previewImport(type,file){if(!file)return;try{const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:"array",cellDates:true}),sheetName=type==="personale"?"PERSONALE":"MEZZI";if(!wb.Sheets[sheetName])throw new Error(`Il file Excel non contiene il foglio ${sheetName}.`);const rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{defval:"",raw:false}),records=type==="personale"?personaleRecords:mezziRecords,seen=new Set();const result=rows.map((raw,index)=>{const row=Object.fromEntries(Object.entries(raw).map(([k,v])=>[core.key(k).replace(/ /g,"_"),v]));const checked=core.validateRow(row,type,records,resolveCommessa),identity=type==="personale"?(row.ID_OPERATORE||row.CODICE_OPERATORE||row.EMAIL_ACCESSO_APP):(row.ID_MEZZO||row.CODICE_MEZZO||row.TARGA),k=core.key(identity);if(k&&seen.has(k)){checked.errors.push("Duplicato nel file.");checked.action="Duplicato";}seen.add(k);return{...checked,rowNumber:index+2};});state.preview={type,file,result};showPreview();}catch(error){alert(error.message||"Non è stato possibile leggere la matrice.");}}
  function showPreview(){const {type,result}=state.preview,errors=result.filter(r=>r.errors.length),removals=result.reduce((n,r)=>n+r.removed.length,0);openModal(`<div class="registry-dialog-head"><h2>Anteprima importazione ${type}</h2><button class="registry-close">×</button></div><div class="registry-preview-summary"><span class="status-pill">Righe ${result.length}</span><span class="status-pill ok">Nuovi ${result.filter(r=>r.action==="Nuovo").length}</span><span class="status-pill warn">Aggiorna ${result.filter(r=>r.action==="Aggiorna").length}</span><span class="status-pill bad">Errori ${errors.length}</span></div>${removals?`<p class="registry-warning"><strong>Attenzione: questa operazione rimuoverà ${removals} abilitazioni. È richiesta conferma esplicita.</strong></p>`:""}<table class="registry-preview-table"><thead><tr><th>Riga</th><th>Record</th><th>Azione</th><th>Abilitazioni</th><th>Controlli</th></tr></thead><tbody>${result.map(r=>`<tr><td data-label="Riga">${r.rowNumber}</td><td data-label="Record">${esc(r.row.CODICE_OPERATORE||r.row.CODICE_MEZZO||`${r.row.NOME||""} ${r.row.COGNOME||""}`)}</td><td data-label="Azione">${r.action}</td><td data-label="Abilitazioni">Attuali ${r.current.length}; +${r.added.length}; −${r.removed.length}; finali ${r.finalIds.length}</td><td data-label="Controlli"><span class="registry-error">${esc(r.errors.join(" "))}</span><span class="registry-warning">${esc(r.warnings.join(" "))}</span></td></tr>`).join("")}</tbody></table><div class="registry-dialog-actions"><button class="btn registry-close">Annulla</button><button id="confirm-import" class="btn btn-primary" ${errors.length?"disabled":""}>Conferma importazione</button></div>`);modal().querySelectorAll(".registry-close").forEach(x=>x.addEventListener("click",closeModal));modal().querySelector("#confirm-import")?.addEventListener("click",()=>confirmImport(removals));}
  async function confirmImport(removals){if(!state.preview||!isManager())return;if(removals&&!window.confirm(`Confermi esplicitamente la rimozione di ${removals} abilitazioni?`))return;const {type,file,result}=state.preview,batch=db.batch(),collection=type==="personale"?getPersonaleCollectionName():getMezziCollectionName(),backup=db.collection("registryImportBackups").doc(),previous=result.filter(r=>r.existing).map(r=>({id:r.existing.id,data:r.existing}));batch.set(backup,{registry:type,fileName:file.name,createdBy:currentUser?.uid||"",createdAt:firebase.firestore.FieldValue.serverTimestamp(),previous,createdIds:[]});for(const item of result){const r=item.row,isPerson=type==="personale",payload=isPerson?{codiceOperatore:r.CODICE_OPERATORE,nome:r.NOME,cognome:r.COGNOME,fullName:`${r.COGNOME||""} ${r.NOME||""}`.trim(),stato:r.STATO||undefined,telefono:r.TELEFONO||undefined,email:r.EMAIL_ACCESSO_APP||r.EMAIL||undefined,mansione:r.MANSIONE||r.RUOLO||undefined,note:r.NOTE||undefined,enabledCommessaIds:item.finalIds}:{codiceMezzo:r.CODICE_MEZZO,nId:r.CODICE_MEZZO,nome:r.CODICE_MEZZO,targa:r.TARGA||undefined,categoria:r.CATEGORIA,marca:r.MARCA||undefined,modello:r.MODELLO||undefined,stato:r.STATO,note:r.NOTE||undefined};Object.keys(payload).forEach(k=>payload[k]===undefined||payload[k]===""&&!(["nome","cognome","codiceMezzo"].includes(k))?delete payload[k]:0);payload.updatedAt=firebase.firestore.FieldValue.serverTimestamp();const ref=item.existing?db.collection(collection).doc(item.existing.id):db.collection(collection).doc();if(!item.existing)payload.createdAt=firebase.firestore.FieldValue.serverTimestamp();batch.set(ref,payload,{merge:true});if(isPerson)item.added.concat(item.removed).forEach(cid=>batch.set(db.collection("operatorCommessaHistory").doc(),{operatorId:ref.id,commessaId:cid,action:item.added.includes(cid)?"enabled":"disabled",changedBy:currentUser?.uid||"",changedAt:firebase.firestore.FieldValue.serverTimestamp(),reason:`importazione ${file.name}`}));}await batch.commit();alert(`Importazione completata: ${result.length} righe elaborate.`);closeModal();}
  const oldPersonnel=typeof renderPersonaleList==="function"?renderPersonaleList:null,oldVehicles=typeof renderMezziList==="function"?renderMezziList:null;if(oldPersonnel)renderPersonaleList=function(){enhancePanels();};if(oldVehicles)renderMezziList=function(){enhancePanels();};document.addEventListener("DOMContentLoaded",enhancePanels);setTimeout(enhancePanels,0);
})();
