(function () {
  "use strict";
  const core = globalThis.HeraManagementCore;
  if (!core) return;
  const state = { personnelFilter: "Tutti", vehicleFilter: "Tutti", personnelQuery: "", vehicleQuery: "", preview: null };
  const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const isManager = () => typeof canManageData === "function" && canManageData();
  const commesse = () => Array.from(commesseById?.entries?.() || []).map(([id, value]) => ({ id, ...value }));
  const resolveCommessa = (value) => { const target = core.key(value); return commesse().find((c) => [c.id,c.codice,c.nome].some((v) => core.key(v) === target))?.id || ""; };
  const enabledIds = (person) => core.legacyEnabledIds(person, resolveCommessa);
  const displayPerson = (p) => typeof getPersonaleDisplayName === "function" ? getPersonaleDisplayName(p) : `${p.cognome || ""} ${p.nome || ""}`.trim();
  const statusClass = (status) => /attivo|disponibile/i.test(status) ? "ok" : /assente|ferie|malattia|permesso|riposo|manutenzione|assegnato|in uso/i.test(status) ? "warn" : /sospeso|cessato|guasto|fuori servizio|dismesso/i.test(status) ? "bad" : "";
  const modal = () => { let el=document.getElementById("registry-modal"); if(!el){el=document.createElement("div");el.id="registry-modal";el.className="registry-modal hidden";el.innerHTML='<div class="registry-dialog" role="dialog" aria-modal="true"></div>';document.body.appendChild(el);el.addEventListener("click",e=>{if(e.target===el)closeModal();});} return el; };
  const closeModal = () => { modal().classList.add("hidden"); modal().querySelector(".registry-dialog").innerHTML=""; state.preview=null; };
  const openModal = (html) => { const el=modal();el.querySelector(".registry-dialog").innerHTML=html;el.classList.remove("hidden");el.querySelector(".registry-close")?.addEventListener("click",closeModal); };
  const managerActions = (type) => isManager() ? `<button class="btn btn-primary" data-new="${type}">+ Nuovo ${type === "personale" ? "operatore" : "mezzo"}</button><button class="btn" data-import="${type}">Importa matrice</button><button class="btn" data-template="${type}">Scarica matrice</button><button class="btn" data-export="${type}">Esporta elenco</button><button class="btn" data-undo="${type}">Annulla ultima importazione</button><button class="btn" data-sheet-link="${type}">Collega Foglio Google</button><button class="btn" data-sheet-sync="${type}">Sincronizza adesso</button><button class="btn" data-sheet-open="${type}">Apri Foglio Google</button><button class="btn" data-sheet-settings="${type}">Impostazioni sincronizzazione</button><button class="btn" data-sheet-unlink="${type}">Scollega Foglio</button>` : "";

  function enhancePanels() {
    const pp=document.getElementById("panel-personale"), vp=document.getElementById("panel-mezzi");
    if(pp&&!pp.dataset.v2){pp.dataset.v2="1";pp.innerHTML='<div id="personnel-v2" class="registry-v2"></div>';}
    if(vp&&!vp.dataset.v2){vp.dataset.v2="1";vp.innerHTML='<div id="vehicles-v2" class="registry-v2"></div>';}
    renderPersonnel();renderVehicles();
  }
  function statsMarkup(values){return `<div class="registry-summary">${values.map(([n,v])=>`<div class="registry-stat"><strong>${v}</strong><small>${esc(n)}</small></div>`).join("")}</div>`;}
  function bindToolbar(root,type){
    root.querySelector("[data-search]")?.addEventListener("input",e=>{state[type==="personale"?"personnelQuery":"vehicleQuery"]=e.target.value;type==="personale"?renderPersonnel():renderVehicles();});
    root.querySelector("[data-filter]")?.addEventListener("change",e=>{state[type==="personale"?"personnelFilter":"vehicleFilter"]=e.target.value;type==="personale"?renderPersonnel():renderVehicles();});
    root.querySelector("[data-new]")?.addEventListener("click",()=>openEditor(type));
    root.querySelector("[data-template]")?.addEventListener("click",()=>downloadWorkbook(type,type==="personale"?personaleRecords:mezziRecords));
    root.querySelector("[data-export]")?.addEventListener("click",()=>downloadWorkbook(type,type==="personale"?personaleRecords:mezziRecords));
    root.querySelector("[data-import]")?.addEventListener("click",()=>chooseImport(type));
    root.querySelector("[data-undo]")?.addEventListener("click",()=>undoLastImport(type));
    if(window.RegistryGoogleSheetSync) window.RegistryGoogleSheetSync.bind(root,type);
  }
  function renderPersonnel(){
    const root=document.getElementById("personnel-v2");if(!root||typeof personaleRecords==="undefined")return;
    const all=personaleRecords||[], q=core.key(state.personnelQuery), filter=state.personnelFilter;
    const rows=all.filter(p=>{const ids=enabledIds(p), text=core.key([displayPerson(p),p.codiceOperatore,p.email,p.telefono,p.mansione,p.stato].join(" "));return(!q||text.includes(q))&&(filter==="Tutti"||(filter==="Abilitati"?ids.length>0:filter==="Non abilitati"?ids.length===0:core.key(p.stato||"Attivo")===core.key(filter)));});
    const active=all.filter(p=>core.key(p.stato||"Attivo")==="ATTIVO").length, absent=all.filter(p=>["ASSENTE","FERIE","MALATTIA","PERMESSO","INFORTUNIO"].includes(core.key(p.stato))).length;
    root.innerHTML=`<div class="registry-head"><div><h2>PERSONALE</h2><small>${rows.length} risultati</small></div><div class="registry-actions">${managerActions("personale")}</div></div>${statsMarkup([["Totale operatori",all.length],["Attivi",active],["Assenti oggi",absent],["Abilitati",all.filter(p=>enabledIds(p).length).length],["Non abilitati",all.filter(p=>!enabledIds(p).length).length]])}<div class="registry-filterbar"><input data-search type="search" value="${esc(state.personnelQuery)}" placeholder="Cerca nome, codice, email, ruolo…"><select data-filter>${["Tutti","Attivo","Assente","Ferie","Malattia","Non disponibile","Cessato","Abilitati","Non abilitati"].map(v=>`<option ${v===filter?"selected":""}>${v}</option>`).join("")}</select></div><div class="registry-grid">${rows.map(personCard).join("")||'<p class="muted">Nessun operatore corrisponde ai filtri.</p>'}</div>`;
    bindToolbar(root,"personale");root.querySelectorAll("[data-enabled]").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();openEnabled(b.dataset.enabled);}));root.querySelectorAll("[data-person]").forEach(c=>c.addEventListener("click",()=>openEditor("personale",c.dataset.person)));
  }
  function personCard(p){const name=displayPerson(p)||"Senza nome",ids=enabledIds(p),status=p.stato||"Attivo",initials=name.split(" ").slice(0,2).map(v=>v[0]).join("").toUpperCase();return `<article class="registry-card" data-person="${esc(p.id)}"><button class="registry-more" aria-label="Azioni">⋮</button><div class="registry-card-head"><span class="registry-avatar">${esc(initials)}</span><div><h3>${esc(name)}</h3><span class="status-pill ${statusClass(status)}">${esc(status)}</span></div></div><p>${esc(p.mansione||p.ruolo||"Mansione non indicata")}${p.telefono?` • ${esc(p.telefono)}`:""}</p><p>${esc(p.squadra||"Nessuna squadra")} • ${esc(p.commessaOggi||"Nessuna commessa oggi")}</p><button class="registry-link" data-enabled="${esc(p.id)}">Commesse abilitate: ${ids.length}</button></article>`;}
  function inferCategory(m){const code=String(m.codiceMezzo||m.nId||m.nome||"").toUpperCase();if(/^MA/.test(code))return"Escavatore";if(/^A/.test(code))return"Camion";if(/^T/.test(code))return"Trattore grande";if(/^R/.test(code))return"Trattore piccolo";return"Attrezzatura";}
  function renderVehicles(){const root=document.getElementById("vehicles-v2");if(!root||typeof mezziRecords==="undefined")return;const all=mezziRecords||[],q=core.key(state.vehicleQuery),filter=state.vehicleFilter;const rows=all.filter(m=>(!q||core.key([m.nId,m.codiceMezzo,m.targa,m.marca,m.modello,m.categoria,m.stato].join(" ")).includes(q))&&(filter==="Tutti"||core.key(m.stato||"Disponibile")===core.key(filter)));root.innerHTML=`<div class="registry-head"><div><h2>MEZZI</h2><small>${rows.length} risultati</small></div><div class="registry-actions">${managerActions("mezzi")}</div></div>${statsMarkup([["Totale mezzi",all.length],["Disponibili",all.filter(m=>core.key(m.stato||"Disponibile")==="DISPONIBILE").length],["In uso",all.filter(m=>core.key(m.stato)==="IN USO").length],["In manutenzione",all.filter(m=>core.key(m.stato)==="IN MANUTENZIONE").length],["Guasti",all.filter(m=>core.key(m.stato)==="GUASTO").length]])}<div class="registry-filterbar"><input data-search type="search" value="${esc(state.vehicleQuery)}" placeholder="Cerca codice, targa, marca, modello…"><select data-filter>${["Tutti",...core.VEHICLE_STATUSES].map(v=>`<option ${v===filter?"selected":""}>${v}</option>`).join("")}</select></div><div class="registry-grid">${rows.map(vehicleCard).join("")||'<p class="muted">Nessun mezzo corrisponde ai filtri.</p>'}</div>`;bindToolbar(root,"mezzi");root.querySelectorAll("[data-vehicle]").forEach(c=>c.addEventListener("click",()=>openEditor("mezzi",c.dataset.vehicle)));}
  function vehicleCard(m){const code=m.codiceMezzo||m.nId||m.nome||m.id,status=m.stato||"Disponibile";return `<article class="registry-card" data-vehicle="${esc(m.id)}"><button class="registry-more" aria-label="Azioni">⋮</button><div class="registry-card-head"><span class="registry-avatar">🚜</span><div><h3>${esc(code)}${m.marca||m.modello?` • ${esc([m.marca,m.modello].filter(Boolean).join(" "))}`:""}</h3><span class="status-pill ${statusClass(status)}">${esc(status)}</span></div></div><p>${m.targa?`Targa ${esc(m.targa)}`:"Senza targa"}</p><p>${esc(m.categoria||inferCategory(m))} • ${esc(m.squadraAssegnata||"Non assegnato")}</p><p>${m.dataRevisione?`Prossima revisione: ${esc(m.dataRevisione)}`:"Nessuna scadenza indicata"}</p></article>`;}

  function openEnabled(id){const person=personaleRecords.find(p=>p.id===id);if(!person)return;const selected=new Set(enabledIds(person));openModal(`<div class="registry-dialog-head"><h2>Commesse abilitate – ${esc(displayPerson(person))}</h2><button class="registry-close">×</button></div><input id="enabled-search" type="search" placeholder="Cerca commessa"><p><strong id="enabled-count">${selected.size} commesse abilitate</strong></p><div class="registry-check-list">${commesse().map(c=>`<label class="registry-check" data-search-text="${esc(core.key(`${c.codice} ${c.nome}`))}"><input type="checkbox" value="${esc(c.id)}" ${selected.has(c.id)?"checked":""} ${isManager()?"":"disabled"}><span><strong>${esc(c.nome||c.id)}</strong><br><small>${esc(c.codice||c.id)} • ${esc(c.stato||"Attiva")}</small></span></label>`).join("")}</div><div class="registry-dialog-actions"><button class="btn registry-close">Annulla</button>${isManager()?'<button id="enabled-save" class="btn btn-primary">Salva modifiche</button>':""}</div>`);const dialog=modal();const update=()=>dialog.querySelector("#enabled-count").textContent=`${dialog.querySelectorAll('.registry-check input:checked').length} commesse abilitate`;dialog.querySelectorAll("input[type=checkbox]").forEach(x=>x.addEventListener("change",update));dialog.querySelector("#enabled-search").addEventListener("input",e=>dialog.querySelectorAll(".registry-check").forEach(x=>x.hidden=!x.dataset.searchText.includes(core.key(e.target.value))));dialog.querySelectorAll(".registry-close").forEach(x=>x.addEventListener("click",closeModal));dialog.querySelector("#enabled-save")?.addEventListener("click",async()=>{const next=[...dialog.querySelectorAll('.registry-check input:checked')].map(x=>x.value),before=enabledIds(person);if(!window.confirm(`Confermare ${next.length} commesse abilitate? I dati storici restano invariati.`))return;const batch=db.batch(),ref=db.collection(getPersonaleCollectionName()).doc(id);batch.set(ref,{enabledCommessaIds:core.unique(next),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});[...new Set([...before,...next])].forEach(cid=>{const action=next.includes(cid)&&!before.includes(cid)?"enabled":!next.includes(cid)&&before.includes(cid)?"disabled":"";if(action){const h=db.collection("operatorCommessaHistory").doc();batch.set(h,{operatorId:id,commessaId:cid,action,changedBy:currentUser?.uid||"",changedAt:firebase.firestore.FieldValue.serverTimestamp(),reason:"modifica manuale"});}});await batch.commit();closeModal();});}

  const availableAppUsers = (currentOperatorId = "") => (typeof platformUsers === "undefined" ? [] : platformUsers)
    .map(core.normalizeAppUser)
    .filter((user) => user.uid && !personaleRecords.some((person) => person.id !== currentOperatorId && person.linkedUserId === user.uid));

  function accountMarkup(person) {
    if (!person.id) return "";
    const user = (typeof platformUsers === "undefined" ? [] : platformUsers).find((item) => String(item.id || item.uid) === String(person.linkedUserId));
    const profile = user ? core.normalizeAppUser(user) : null;
    return `<section class="registry-account"><h3>ACCOUNT APP</h3><div class="registry-account-summary">${person.photoURL ? `<img src="${esc(person.photoURL)}" alt="Foto profilo">` : '<span class="registry-avatar">👤</span>'}<div><strong>${esc(profile?.displayName || person.googleDisplayName || "Profilo non collegato")}</strong><small>${esc(person.linkedUserEmail || profile?.email || "Nessuna email di accesso")}</small><small>Profilo collegato: ${person.linkedUserId ? "Sì" : "No"}${profile ? ` • Email verificata: ${profile.emailVerified ? "Sì" : "No"} • Ruolo: ${esc(profile.role)}` : ""}</small>${profile?.lastLoginAt ? `<small>Ultimo accesso: ${esc(String(profile.lastLoginAt))}</small>` : ""}</div></div>${isManager() ? `<div class="registry-account-actions"><button type="button" class="btn" data-link-user="${esc(person.id)}">${person.linkedUserId ? "Cambia collegamento" : "Collega utente"}</button>${person.linkedUserId ? `<button type="button" class="btn" data-unlink-user="${esc(person.id)}">Scollega utente</button>` : ""}<button type="button" class="btn" data-open-users>Apri gestione utente</button></div>` : ""}</section>`;
  }

  function openEditor(type, id = "", sourceUser = null) {
    const isPerson = type === "personale";
    const original = (isPerson ? personaleRecords : mezziRecords).find((item) => item.id === id) || {};
    const profile = sourceUser ? core.normalizeAppUser(sourceUser) : null;
    const proposal = profile ? core.proposeDisplayName(profile.displayName) : {};
    const record = profile ? { ...original, nome: original.nome || proposal.nome, cognome: original.cognome || proposal.cognome, email: original.email || profile.email, photoURL: original.photoURL || profile.photoURL } : original;
    const createModes = isPerson && !id ? `<div class="registry-mode-tabs"><button type="button" class="btn ${profile ? "" : "btn-primary"}" data-manual-mode>Inserimento manuale</button><button type="button" class="btn ${profile ? "btn-primary" : ""}" data-user-mode>Crea da utente dell’app</button></div>` : "";
    openModal(`<div class="registry-dialog-head"><h2>${id ? "Modifica" : "Nuovo"} ${isPerson ? "operatore" : "mezzo"}</h2><button class="registry-close">×</button></div>${createModes}<form id="registry-editor" class="personale-fields-grid">${isPerson ? `<input name="nome" required placeholder="Nome" value="${esc(record.nome)}"><input name="cognome" required placeholder="Cognome" value="${esc(record.cognome)}"><input name="codiceOperatore" placeholder="Codice operatore" value="${esc(record.codiceOperatore)}"><input name="mansione" placeholder="Mansione" value="${esc(record.mansione)}"><input name="telefono" placeholder="Telefono" value="${esc(record.telefono)}"><input name="email" type="email" placeholder="Email" value="${esc(record.email)}"><select name="stato">${core.PERSON_STATUSES.map((value) => `<option ${value === (record.stato || "Attivo") ? "selected" : ""}>${value}</option>`).join("")}</select>${profile ? `<div class="registry-google-preview"><strong>Anteprima profilo Google</strong><span>${profile.photoURL ? `<img src="${esc(profile.photoURL)}" alt="Foto Google">` : "👤"}</span><small>${esc(profile.displayName)} • ${esc(profile.email)} • ${profile.emailVerified ? "Email verificata" : "Email non verificata"}</small><small>La suddivisione del nome è una proposta: correggila prima di salvare.</small></div>` : ""}` : `<input name="codiceMezzo" required placeholder="Codice mezzo" value="${esc(record.codiceMezzo || record.nId || record.nome)}"><input name="targa" placeholder="Targa" value="${esc(record.targa)}"><select name="categoria">${core.VEHICLE_CATEGORIES.map((value) => `<option ${value === (record.categoria || inferCategory(record)) ? "selected" : ""}>${value}</option>`).join("")}</select><input name="marca" placeholder="Marca" value="${esc(record.marca)}"><input name="modello" placeholder="Modello" value="${esc(record.modello)}"><select name="stato">${core.VEHICLE_STATUSES.map((value) => `<option ${value === (record.stato || "Disponibile") ? "selected" : ""}>${value}</option>`).join("")}</select>`}<textarea name="note" placeholder="Note">${esc(record.note)}</textarea><div class="registry-dialog-actions"><button type="button" class="btn registry-close">Annulla</button><button class="btn btn-primary">${profile ? "Conferma e crea operatore" : "Salva"}</button></div></form>${isPerson ? accountMarkup(original) : ""}`);
    const dialog = modal();
    dialog.querySelectorAll(".registry-close").forEach((button) => button.addEventListener("click", closeModal));
    dialog.querySelector("[data-user-mode]")?.addEventListener("click", () => openUserPicker({ create: true }));
    dialog.querySelector("[data-manual-mode]")?.addEventListener("click", () => openEditor("personale"));
    dialog.querySelector("[data-link-user]")?.addEventListener("click", () => openUserPicker({ operatorId: id }));
    dialog.querySelector("[data-unlink-user]")?.addEventListener("click", () => unlinkUser(id));
    dialog.querySelector("[data-open-users]")?.addEventListener("click", () => { closeModal(); document.getElementById("open-panel-utenti")?.click(); });
    dialog.querySelector("form").addEventListener("submit", async (event) => {
      event.preventDefault();
      const data = Object.fromEntries(new FormData(event.target));
      if (isPerson) data.fullName = `${data.cognome} ${data.nome}`.trim();
      else { data.nId = data.codiceMezzo; data.nome = data.codiceMezzo; }
      data.updatedAt = firebase.firestore.FieldValue.serverTimestamp();
      const collection = isPerson ? getPersonaleCollectionName() : getMezziCollectionName();
      if (profile) {
        const conflicts = core.findUserLinkConflicts(profile, personaleRecords, id);
        if (conflicts.duplicateUid) return alert(`Questo utente dell’app è già collegato all’operatore ${displayPerson(conflicts.linked[0])}.`);
        if (conflicts.ambiguousEmail) return alert("Esistono più operatori con questa email. È necessario scegliere manualmente il profilo corretto.");
        if (!id && conflicts.emailMatches.length === 1) return alert(`Esiste già l’operatore ${displayPerson(conflicts.emailMatches[0])} con questa email. Apri la sua scheda e usa “Collega utente” per evitare duplicati.`);
      }
      let operatorId = id;
      if (!operatorId) {
        data.createdAt = firebase.firestore.FieldValue.serverTimestamp();
        if (isPerson) data.enabledCommessaIds = [];
        const ref = db.collection(collection).doc(); operatorId = ref.id;
        if (profile) Object.assign(data, core.buildGoogleLinkPatch({}, profile, { nome: data.nome, cognome: data.cognome }), { linkedAt: firebase.firestore.FieldValue.serverTimestamp(), linkedBy: currentUser?.uid || "" });
        await ref.set(data);
      } else await db.collection(collection).doc(operatorId).set(data, { merge: true });
      if (profile) await finalizeUserLink(operatorId, profile, "linked", true);
      closeModal();
    });
  }

  function openUserPicker({ create = false, operatorId = "" } = {}) {
    const users = availableAppUsers(operatorId);
    openModal(`<div class="registry-dialog-head"><h2>${create ? "Crea da utente dell’app" : "Collega utente dell’app"}</h2><button class="registry-close">×</button></div><input id="app-user-search" type="search" placeholder="Cerca nome, cognome o email"><div class="registry-user-list">${users.map((raw) => `<button type="button" class="registry-user-row" data-app-user="${esc(raw.uid)}" data-search-text="${esc(core.key(`${raw.displayName} ${raw.email}`))}">${raw.photoURL ? `<img src="${esc(raw.photoURL)}" alt="">` : '<span class="registry-avatar">👤</span>'}<span><strong>${esc(raw.displayName || "Nome non disponibile")}</strong><small>${esc(raw.email)}</small><small>${esc(raw.accountStatus || "Stato non indicato")} • ${esc(raw.role)}${raw.firstLoginAt ? ` • Primo accesso: ${esc(String(raw.firstLoginAt))}` : ""}</small></span></button>`).join("") || '<p class="muted">Tutti gli utenti risultano già collegati.</p>'}</div><div class="registry-dialog-actions"><button class="btn registry-close">Annulla</button></div>`);
    const dialog = modal();
    dialog.querySelectorAll(".registry-close").forEach((button) => button.addEventListener("click", closeModal));
    dialog.querySelector("#app-user-search").addEventListener("input", (event) => dialog.querySelectorAll(".registry-user-row").forEach((row) => { row.hidden = !row.dataset.searchText.includes(core.key(event.target.value)); }));
    dialog.querySelectorAll("[data-app-user]").forEach((button) => button.addEventListener("click", () => {
      const source = (typeof platformUsers === "undefined" ? [] : platformUsers).find((user) => String(user.id || user.uid) === button.dataset.appUser);
      if (create) openEditor("personale", "", source); else previewUserLink(operatorId, source);
    }));
  }

  function maskedUid(uid) { const value = String(uid || ""); return value.length < 9 ? "••••" : `${value.slice(0, 4)}••••${value.slice(-4)}`; }
  function previewUserLink(operatorId, user) {
    const person = personaleRecords.find((item) => item.id === operatorId); const profile = core.normalizeAppUser(user);
    if (!person || !profile.uid) return;
    const conflicts = core.findUserLinkConflicts(profile, personaleRecords, operatorId);
    if (conflicts.duplicateUid) return alert(`Questo utente dell’app è già collegato all’operatore ${displayPerson(conflicts.linked[0])}.`);
    openModal(`<div class="registry-dialog-head"><h2>Conferma collegamento</h2><button class="registry-close">×</button></div><div class="registry-link-preview"><section><h3>Operatore esistente</h3><strong>${esc(displayPerson(person))}</strong><p>Codice: ${esc(person.codiceOperatore || "-")}<br>Email: ${esc(person.email || "-")}</p></section><section><h3>Utente dell’app</h3><strong>${esc(profile.displayName || "-")}</strong><p>Email Google: ${esc(profile.email || "-")}<br>UID: ${esc(maskedUid(profile.uid))}</p></section></div><p>Il collegamento non modifica mansione, squadre, ore, documenti o commesse abilitate.</p><div class="registry-dialog-actions"><button class="btn registry-close">Annulla</button><button id="confirm-user-link" class="btn btn-primary">Collega profili</button></div>`);
    modal().querySelectorAll(".registry-close").forEach((button) => button.addEventListener("click", closeModal));
    modal().querySelector("#confirm-user-link").addEventListener("click", async () => { await finalizeUserLink(operatorId, profile, person.linkedUserId ? "changed" : "linked"); closeModal(); });
  }

  async function finalizeUserLink(operatorId, user, action = "linked", alreadyPatched = false) {
    const profile = core.normalizeAppUser(user); const person = personaleRecords.find((item) => item.id === operatorId) || {};
    const conflicts = core.findUserLinkConflicts(profile, personaleRecords, operatorId);
    if (conflicts.duplicateUid) throw new Error("Questo UID è già collegato a un altro operatore.");
    const operatorRef = db.collection(getPersonaleCollectionName()).doc(operatorId), lockRef = db.collection("userOperatorLinks").doc(profile.uid), historyRef = db.collection("operatorUserLinkHistory").doc();
    await db.runTransaction(async (transaction) => {
      const lock = await transaction.get(lockRef);
      if (lock.exists && lock.data().operatorId !== operatorId) throw new Error("Questo utente dell’app è già collegato a un altro operatore.");
      if (person.linkedUserId && person.linkedUserId !== profile.uid) transaction.delete(db.collection("userOperatorLinks").doc(person.linkedUserId));
      if (!alreadyPatched) transaction.set(operatorRef, { ...core.buildGoogleLinkPatch(person, profile), linkedAt: firebase.firestore.FieldValue.serverTimestamp(), linkedBy: currentUser?.uid || "", updatedAt: firebase.firestore.FieldValue.serverTimestamp() }, { merge: true });
      transaction.set(lockRef, { operatorId, linkedUserEmail: profile.email, linkedAt: firebase.firestore.FieldValue.serverTimestamp(), linkedBy: currentUser?.uid || "" });
      transaction.set(historyRef, { operatorId, linkedUserId: profile.uid, action, administrator: currentUser?.uid || "", changedAt: firebase.firestore.FieldValue.serverTimestamp(), linkedUserEmail: profile.email, source: "google" });
    });
  }

  async function unlinkUser(operatorId) {
    const person = personaleRecords.find((item) => item.id === operatorId); if (!person?.linkedUserId || !isManager()) return;
    if (!window.confirm(`Vuoi scollegare l’accesso Google dalla scheda di ${displayPerson(person)}? I dati lavorativi e lo storico dell’operatore non saranno eliminati.`)) return;
    const historyRef = db.collection("operatorUserLinkHistory").doc(), operatorRef = db.collection(getPersonaleCollectionName()).doc(operatorId), lockRef = db.collection("userOperatorLinks").doc(person.linkedUserId), remove = firebase.firestore.FieldValue.delete();
    await db.runTransaction(async (transaction) => {
      transaction.set(operatorRef, { linkedUserId: remove, linkedUserEmail: remove, linkedAuthProvider: remove, linkedAt: remove, linkedBy: remove, profileSource: remove, updatedAt: firebase.firestore.FieldValue.serverTimestamp() }, { merge: true });
      transaction.delete(lockRef);
      transaction.set(historyRef, { operatorId, linkedUserId: person.linkedUserId, action: "unlinked", administrator: currentUser?.uid || "", changedAt: firebase.firestore.FieldValue.serverTimestamp(), linkedUserEmail: person.linkedUserEmail || "", source: "google" });
    });
    closeModal();
  }

  const PERSON_FIELD_MAP={CODICE_OPERATORE:"codiceOperatore",NOME:"nome",COGNOME:"cognome",CODICE_FISCALE:"codiceFiscale",DATA_NASCITA:"dataNascita",LUOGO_NASCITA:"luogoNascita",TELEFONO:"telefono",EMAIL:"email",RUOLO:"ruolo",MANSIONE:"mansione",LIVELLO:"livello",TIPO_CONTRATTO:"tipoContratto",DATA_ASSUNZIONE:"dataAssunzione",DATA_FINE_CONTRATTO:"dataFineContratto",MATRICOLA:"matricola",AZIENDA:"azienda",SEDE:"sede",RESPONSABILE:"responsabile",STATO:"stato",SQUADRA:"squadra",COMMESSE:"commesse",PATENTE:"patente",ABILITAZIONI:"abilitazioni",DATA_SCADENZA_PATENTE:"dataScadenzaPatente",DATA_SCADENZA_VISITA_MEDICA:"dataScadenzaVisitaMedica",DATA_SCADENZA_CONTRATTO:"dataScadenzaContratto",CONTATTO_EMERGENZA:"contattoEmergenza",TELEFONO_EMERGENZA:"telefonoEmergenza",NOTE:"note",ATTIVO:"attivo",EMAIL_ACCESSO_APP:"emailAccessoApp",RUOLO_APP:"ruoloApp",CONSENTI_ACCESSO_APP:"consentiAccessoApp"};
  const VEHICLE_FIELD_MAP={CODICE_MEZZO:"codiceMezzo",TARGA:"targa",CATEGORIA:"categoria",MARCA:"marca",MODELLO:"modello",ANNO_IMMATRICOLAZIONE:"annoImmatricolazione",NUMERO_TELAIO:"numeroTelaio",ALIMENTAZIONE:"alimentazione",CILINDRATA:"cilindrata",POTENZA:"potenza",CHILOMETRI:"chilometri",ORE_MOTORE:"oreMotore",PORTATA:"portata",PESO:"peso",NUMERO_POSTI:"numeroPosti",AZIENDA_PROPRIETARIA:"aziendaProprietaria",STATO:"stato",SQUADRA_ASSEGNATA:"squadraAssegnata",OPERATORE_RESPONSABILE:"operatoreResponsabile",COMMESSE:"commesse",LUOGO_DEPOSITO:"luogoDeposito",DATA_REVISIONE:"dataRevisione",DATA_SCADENZA_ASSICURAZIONE:"dataScadenzaAssicurazione",DATA_SCADENZA_BOLLO:"dataScadenzaBollo",DATA_PROSSIMA_MANUTENZIONE:"dataProssimaManutenzione",DATA_SCADENZA_TARATURA:"dataScadenzaTaratura",DATA_INIZIO_NOLEGGIO:"dataInizioNoleggio",DATA_FINE_NOLEGGIO:"dataFineNoleggio",FORNITORE_NOLEGGIO:"fornitoreNoleggio",NUMERO_POLIZZA:"numeroPolizza",COMPAGNIA_ASSICURATIVA:"compagniaAssicurativa",NOTE:"note",ATTIVO:"attivo",FOTO_URL:"fotoUrl",DOCUMENTI_URL:"documentiUrl"};
  const sheetValue=value=>value?.toDate instanceof Function?value.toDate().toLocaleDateString("it-IT"):value??"";
  function workbookRows(type,records){const isPerson=type==="personale",map=isPerson?PERSON_FIELD_MAP:VEHICLE_FIELD_MAP;return records.map(r=>{const row={};(isPerson?core.PERSONNEL_COLUMNS:core.VEHICLE_COLUMNS).forEach(column=>{row[column]=sheetValue(map[column]?r[map[column]]:"");});row[isPerson?"ID_OPERATORE":"ID_MEZZO"]=r.id;if(isPerson){row.EMAIL_ACCESSO_APP=r.emailAccessoApp||r.email||"";row.COMMESSE_ABILITATE=enabledIds(r).join("; ");row.MODALITA_AGGIORNAMENTO_COMMESSE="NON_MODIFICARE";row.MANTIENI_ABILITAZIONI_ESISTENTI="SÌ";row.LINKED_USER_ID=r.linkedUserId||"";row.LINKED_USER_EMAIL=r.linkedUserEmail||"";row.PROFILO_COLLEGATO=r.linkedUserId?"SÌ":"NO";row.FONTE_FOTO_PROFILO=String(r.profilePhotoSource||"").toUpperCase();}else{row.CODICE_MEZZO=r.codiceMezzo||r.nId||r.nome||"";row.CATEGORIA=r.categoria||inferCategory(r);row.STATO=r.stato||"Disponibile";}return row;});}
  function importPayload(type,item){const isPerson=type==="personale",map=isPerson?PERSON_FIELD_MAP:VEHICLE_FIELD_MAP,payload={};Object.entries(map).forEach(([column,field])=>{const value=core.clean(item.row[column]);if(value)payload[field]=value;});if(isPerson&&core.key(item.row.MODALITA_AGGIORNAMENTO_COMMESSE)!=="NON_MODIFICARE")payload.enabledCommessaIds=item.finalIds;if(!isPerson&&payload.codiceMezzo){payload.nId=payload.codiceMezzo;payload.nome=payload.codiceMezzo;}if(isPerson&&(payload.nome||payload.cognome))payload.fullName=`${payload.cognome||item.existing?.cognome||""} ${payload.nome||item.existing?.nome||""}`.trim();return payload;}
  async function downloadWorkbook(type,records){if(!isManager())return;const isPerson=type==="personale",wb=new ExcelJS.Workbook(),columns=isPerson?core.PERSONNEL_COLUMNS:core.VEHICLE_COLUMNS,name=isPerson?"PERSONALE":"MEZZI",ws=wb.addWorksheet(name,{views:[{state:"frozen",ySplit:1}]});ws.columns=columns.map(c=>({header:c,key:c,width:Math.min(28,Math.max(14,c.length+2)),style:{numFmt:"@"}}));if(isPerson&&!records.length)ws.getColumn("LINKED_USER_ID").hidden=true;workbookRows(type,records).forEach(r=>ws.addRow(r));ws.autoFilter={from:"A1",to:`${ws.getColumn(columns.length).letter}${Math.max(2,ws.rowCount)}`};ws.getRow(1).eachCell(c=>{c.font={bold:true,color:{argb:"FFFFFFFF"}};c.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF1769AA"}};c.alignment={wrapText:true};});[3,4,isPerson?20:2].forEach(i=>ws.getColumn(i).eachCell((c,row)=>{if(row>1)c.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFFFF2CC"}};}));const instructions=wb.addWorksheet("ISTRUZIONI");instructions.addRows([["ISTRUZIONI"],["Compilare le colonne tramite intestazione. Date: GG/MM/AAAA."],["Le celle vuote non cancellano dati esistenti."],["Le commesse multiple sono separate da punto e virgola."],["L'importazione mostra sempre un'anteprima prima del salvataggio."],["Per le abilitazioni il valore predefinito è NON_MODIFICARE e MANTIENI=SÌ."]]);const allowed=wb.addWorksheet("VALORI_AMMESSI");const lists=isPerson?[["STATO",...core.PERSON_STATUSES],["RUOLO_APP","admin","responsabile","operatore","visualizzatore"],["MODALITA_AGGIORNAMENTO_COMMESSE",...core.MODES],["SÌ/NO","SÌ","NO"]]:[["CATEGORIA",...core.VEHICLE_CATEGORIES],["STATO",...core.VEHICLE_STATUSES],["ALIMENTAZIONE","Diesel","Benzina","Elettrico","Ibrido","GPL","Metano","Altro"]];lists.forEach((list,i)=>list.forEach((v,j)=>allowed.getCell(j+1,i+1).value=v));const teams=wb.addWorksheet("SQUADRE_DISPONIBILI");teams.addRow(["NOME"]);const available=wb.addWorksheet("COMMESSE_DISPONIBILI");available.addRow(["ID","CODICE","NOME","STATO"]);commesse().forEach(c=>available.addRow([c.id,c.codice||"",c.nome||"",c.stato||"Attiva"]));if(!isPerson){const people=wb.addWorksheet("PERSONALE_DISPONIBILE");people.addRow(["ID","NOME"]);personaleRecords.filter(p=>core.key(p.stato||"Attivo")==="ATTIVO").forEach(p=>people.addRow([p.id,displayPerson(p)]));}wb.worksheets.slice(1).forEach(s=>{s.getRow(1).font={bold:true};s.protect("hera-support",{selectLockedCells:true});});const blob=new Blob([await wb.xlsx.writeBuffer()],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=isPerson?"Matrice_Personale.xlsx":"Matrice_Mezzi.xlsx";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  async function undoLastImport(type){if(!isManager())return;const snap=await db.collection("registryImportBackups").where("registry","==",type).orderBy("createdAt","desc").limit(1).get();if(snap.empty){alert("Nessuna importazione annullabile trovata.");return;}const backup=snap.docs[0],data=backup.data(),previous=Array.isArray(data.previous)?data.previous:[],createdIds=Array.isArray(data.createdIds)?data.createdIds:[];if(!previous.length&&!createdIds.length){alert("Il backup non contiene modifiche ripristinabili.");return;}if(!window.confirm(`Annullare l’ultima importazione? Saranno ripristinati ${previous.length} record e rimossi ${createdIds.length} record creati da quella importazione. Storico e collegamenti esterni restano invariati.`))return;const collection=type==="personale"?getPersonaleCollectionName():getMezziCollectionName(),batch=db.batch();previous.forEach(item=>batch.set(db.collection(collection).doc(item.id),item.data,{merge:false}));createdIds.forEach(id=>batch.delete(db.collection(collection).doc(id)));batch.delete(backup.ref);await batch.commit();alert(`Importazione annullata: ${previous.length} record ripristinati, ${createdIds.length} nuovi record rimossi.`);}
  function chooseImport(type){const input=document.createElement("input");input.type="file";input.accept=".xlsx,.xls,.csv";input.onchange=()=>previewImport(type,input.files[0]);input.click();}
  async function previewImport(type,file){if(!file)return;try{const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:"array",cellDates:true}),sheetName=type==="personale"?"PERSONALE":"MEZZI";if(!wb.Sheets[sheetName])throw new Error(`Il file Excel non contiene il foglio ${sheetName}.`);const rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{defval:"",raw:false}),records=type==="personale"?personaleRecords:mezziRecords,seen=new Set();const result=rows.map((raw,index)=>{const row=Object.fromEntries(Object.entries(raw).map(([k,v])=>[core.key(k).replace(/ /g,"_"),v]));const checked=core.validateRow(row,type,records,resolveCommessa);if(type==="personale"&&core.clean(row.LINKED_USER_EMAIL)&&core.clean(row.LINKED_USER_EMAIL).toLowerCase()!==core.clean(checked.existing?.linkedUserEmail).toLowerCase()){const candidates=(typeof platformUsers==="undefined"?[]:platformUsers).map(core.normalizeAppUser).filter(u=>u.email===core.clean(row.LINKED_USER_EMAIL).toLowerCase());if(candidates.length!==1)checked.errors.push(candidates.length?"Più utenti dell’app hanno questa email.":"Nessun utente dell’app corrisponde a LINKED_USER_EMAIL.");else{const conflicts=core.findUserLinkConflicts(candidates[0],personaleRecords,checked.existing?.id||"");if(conflicts.duplicateUid)checked.errors.push("L’utente dell’app è già collegato a un altro operatore.");else checked.linkedUser=candidates[0];}}const identities=(type==="personale"?[row.ID_OPERATORE,row.CODICE_OPERATORE,row.EMAIL_ACCESSO_APP,row.EMAIL]:[row.ID_MEZZO,row.CODICE_MEZZO,row.TARGA]).map(core.key).filter(Boolean);if(!identities.length)checked.errors.push("Identificativo mancante.");if(identities.some(value=>seen.has(value))){checked.errors.push("Duplicato nel file.");checked.action="Duplicato";}identities.forEach(value=>seen.add(value));const candidate={...checked,rowNumber:index+2};const payload=importPayload(type,candidate);if(checked.existing&&!checked.errors.length&&!checked.added.length&&!checked.removed.length&&Object.entries(payload).every(([field,value])=>core.key(checked.existing[field])===core.key(value)))candidate.action="Invariato";else if(checked.errors.length)candidate.action="Errore";return candidate;});state.preview={type,file,result};showPreview();}catch(error){alert(error.message||"Non è stato possibile leggere la matrice.");}}
  function showPreview(){const {type,result}=state.preview,errors=result.filter(r=>r.errors.length),removals=result.reduce((n,r)=>n+r.removed.length,0),warnings=result.filter(r=>r.warnings.length);openModal(`<div class="registry-dialog-head"><h2>Anteprima importazione ${type}</h2><button class="registry-close">×</button></div><div class="registry-preview-summary"><span class="status-pill">Righe ${result.length}</span><span class="status-pill ok">Nuovi ${result.filter(r=>r.action==="Nuovo").length}</span><span class="status-pill warn">Aggiornati ${result.filter(r=>r.action==="Aggiorna").length}</span><span class="status-pill">Invariati ${result.filter(r=>r.action==="Invariato").length}</span><span class="status-pill bad">Errori ${errors.length}</span><span class="status-pill warn">Avvisi ${warnings.length}</span></div>${removals?`<p class="registry-warning"><strong>Attenzione: questa operazione rimuoverà ${removals} abilitazioni. È richiesta conferma esplicita.</strong></p>`:""}<table class="registry-preview-table"><thead><tr><th>Riga</th><th>Record</th><th>Azione</th><th>Abilitazioni</th><th>Controlli</th></tr></thead><tbody>${result.map(r=>`<tr><td data-label="Riga">${r.rowNumber}</td><td data-label="Record">${esc(r.row.CODICE_OPERATORE||r.row.CODICE_MEZZO||`${r.row.NOME||""} ${r.row.COGNOME||""}`)}</td><td data-label="Azione">${r.action}</td><td data-label="Abilitazioni">Attuali ${r.current.length}; +${r.added.length}; −${r.removed.length}; finali ${r.finalIds.length}</td><td data-label="Controlli"><span class="registry-error">${esc(r.errors.join(" "))}</span><span class="registry-warning">${esc(r.warnings.join(" "))}</span></td></tr>`).join("")}</tbody></table><div class="registry-dialog-actions"><button class="btn registry-close">Annulla</button><button id="confirm-import" class="btn btn-primary" ${errors.length?"disabled":""}>Conferma importazione</button></div>`);modal().querySelectorAll(".registry-close").forEach(x=>x.addEventListener("click",closeModal));modal().querySelector("#confirm-import")?.addEventListener("click",()=>confirmImport(removals));}
  async function confirmImport(removals){if(!state.preview||!isManager())return;if(removals&&!window.confirm(`Confermi esplicitamente la rimozione di ${removals} abilitazioni?`))return;const {type,file,result}=state.preview,valid=result.filter(item=>!item.errors.length&&item.action!=="Invariato"),batch=db.batch(),collection=type==="personale"?getPersonaleCollectionName():getMezziCollectionName(),backup=db.collection("registryImportBackups").doc(),previous=valid.filter(r=>r.existing).map(r=>({id:r.existing.id,data:r.existing})),createdIds=[],pendingLinks=[];for(const item of valid){const isPerson=type==="personale",payload=importPayload(type,item);payload.updatedAt=firebase.firestore.FieldValue.serverTimestamp();payload.updatedBy=currentUser?.uid||"";const ref=item.existing?db.collection(collection).doc(item.existing.id):db.collection(collection).doc();if(!item.existing){payload.createdAt=firebase.firestore.FieldValue.serverTimestamp();createdIds.push(ref.id);}batch.set(ref,payload,{merge:true});if(isPerson&&item.linkedUser)pendingLinks.push({operatorId:ref.id,user:item.linkedUser});if(isPerson)item.added.concat(item.removed).forEach(cid=>batch.set(db.collection("operatorCommessaHistory").doc(),{operatorId:ref.id,commessaId:cid,action:item.added.includes(cid)?"enabled":"disabled",changedBy:currentUser?.uid||"",changedAt:firebase.firestore.FieldValue.serverTimestamp(),reason:`importazione ${file.name}`}));}batch.set(backup,{registry:type,fileName:file.name,createdBy:currentUser?.uid||"",createdAt:firebase.firestore.FieldValue.serverTimestamp(),previous,createdIds});await batch.commit();for(const link of pendingLinks)await finalizeUserLink(link.operatorId,link.user,"linked");alert(`Importazione completata: ${valid.length} modifiche; ${result.length-valid.length} righe invariate o escluse.`);closeModal();}
  function syncLinkedGoogleProfile(user) {
    if (!user?.uid || typeof personaleRecords === "undefined") return;
    const person = personaleRecords.find((item) => item.linkedUserId === user.uid);
    if (!person) return;
    const patch = core.buildGoogleLoginSyncPatch(person, user);
    patch.googleLastLoginAt = firebase.firestore.FieldValue.serverTimestamp();
    patch.updatedAt = firebase.firestore.FieldValue.serverTimestamp();
    db.collection(getPersonaleCollectionName()).doc(person.id).set(patch, { merge: true }).catch(() => {});
  }
  window.HeraManagementV2={workbookRows,importPayload,previewImport};
  if (typeof auth !== "undefined" && auth?.onAuthStateChanged) auth.onAuthStateChanged((user) => { if (user) setTimeout(() => syncLinkedGoogleProfile(user), 1500); });
  const oldPersonnel=typeof renderPersonaleList==="function"?renderPersonaleList:null,oldVehicles=typeof renderMezziList==="function"?renderMezziList:null;if(oldPersonnel)renderPersonaleList=function(){enhancePanels();};if(oldVehicles)renderMezziList=function(){enhancePanels();};document.addEventListener("DOMContentLoaded",enhancePanels);setTimeout(enhancePanels,0);
})();
