(function installNotificationCenter(){
"use strict";
const C="notifications",L="userAlerts",Q="hera_notification_outbox_v1";
const s={user:null,items:new Map(),sources:new Map(),ready:new Set(),seen:new Set(),unsubs:[],filter:"all",expanded:"",undo:null,touch:null};
const $=(q,r=document)=>r.querySelector(q),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const ms=v=>v?.toMillis?.()||v?.toDate?.().getTime?.()||Date.parse(v||0)||0,key=(c,id)=>`${c}:${id}`,stamp=n=>ms(n.createdAt)||ms(n.receivedAt);
const admin=()=>/^(ionut29019)@gmail\.com$/i.test(s.user?.email||""),today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
function killLegacy(){document.getElementById("received-notification-dialog")?.remove();document.getElementById("user-alert-modal")?.remove();document.querySelectorAll("#notification-inbox-btn:not([data-central-notification-bell='1'])").forEach(x=>x.remove())}
killLegacy();const observer=new MutationObserver(killLegacy);const observe=()=>document.body&&observer.observe(document.body,{childList:true,subtree:true});document.body?observe():addEventListener("DOMContentLoaded",observe,{once:true});
function central(id,d={}){return{id,_key:key(C,id),_collection:C,_legacy:false,...d,title:d.title||"Notifica",message:d.message||d.preview||"",preview:d.preview||d.message||"",recipientUserIds:Array.isArray(d.recipientUserIds)?d.recipientUserIds:[],readBy:d.readBy||{},deletedBy:d.deletedBy||{}}}
function legacy(id,d={}){return{id,_key:key(L,id),_collection:L,_legacy:true,...d,title:d.title||"Avviso importante",message:d.message||d.body||"",preview:d.message||d.body||"",type:d.type||"AVVISO",priority:d.priority||"NORMALE",scopeType:d.sendToAllRegistered?"GLOBALE":"PERSONALE",recipientUserIds:Array.isArray(d.targetUserIds)?d.targetUserIds:[],readBy:{...(d.ackByUserIds||{}),...(d.dismissedByUserIds||{}),...(d.readBy||{})},deletedBy:d.deletedBy||{},attachments:Array.isArray(d.attachments)?d.attachments:[]}}
function visible(n){if(!s.user||n.deletedBy?.[s.user.uid])return false;if(admin())return true;if(n._legacy){const date=String(n.scheduledDateKey||"");if(n.source==="squadra-avviso"||(date&&date>today()&&n.source!=="calendar-absence"))return false;return n.sendToAllRegistered||n.scopeType==="GLOBALE"||n.recipientUserIds.includes(s.user.uid)}return n.scopeType==="GLOBALE"||n.recipientUserIds.includes(s.user.uid)}
const unread=n=>Boolean(s.user&&!n.readBy?.[s.user.uid]),confirmed=n=>Boolean(s.user&&(n.ackByUserIds?.[s.user.uid]||n.dismissedByUserIds?.[s.user.uid]));
const icon=n=>({WORKLIMATE:"🔴",METEO:"⚠️",IMPIANTO_COMPLETATO:"✅",NAVIGAZIONE:"📍",ORE:"🕒",SQUADRA:"👥",MEZZO:"🚚",SYNC_ERROR:"⛔",AVVISO:"🔔"}[n.type]||"🔔");
function ensureUi(){killLegacy();document.getElementById("notification-inbox-btn")?.remove();const b=document.createElement("button");b.id="notification-inbox-btn";b.type="button";b.className="header-icon-btn notification-bell header-action-button header-notification-button";b.dataset.centralNotificationBell="1";b.innerHTML='<span class="header-action-icon" aria-hidden="true">🔔</span><span class="notification-bell-badge" hidden></span><span class="header-action-label">Notifiche</span>';b.title="Centro notifiche";b.setAttribute("aria-label","Apri Centro notifiche");b.onclick=open;$(".logo-head-action-icons")?.prepend(b);if(!$("#notification-center"))document.body.insertAdjacentHTML("beforeend",`<dialog id="notification-center" class="notification-center" aria-labelledby="notification-center-title"><div class="notification-center-shell"><header class="notification-center-head"><div class="notification-center-title-row"><h2 id="notification-center-title">Notifiche</h2><button class="btn" data-nc-close aria-label="Chiudi Centro notifiche">✕</button></div><div class="notification-filter" role="tablist"><button class="btn" data-filter="all" aria-selected="true">TUTTE</button><button class="btn" data-filter="unread" aria-selected="false">NON LETTE</button></div></header><div class="notification-list" role="list"></div><footer class="notification-center-foot"><button class="btn" data-read-all>SEGNA TUTTE COME LETTE</button><button class="btn danger" data-delete-all>ELIMINA TUTTE LE NOTIFICHE</button><button class="btn" data-nc-close>CHIUDI</button></footer></div></dialog>`);const d=$("#notification-center");if(!d.dataset.bound){d.dataset.bound="1";d.onclick=click;d.onkeydown=e=>{if(e.key==="Escape")close()}}return b}
function rows(){return[...s.items.values()].filter(visible).sort((a,b)=>(Number(unread(b)&&b.priority==="CRITICA")-Number(unread(a)&&a.priority==="CRITICA"))||stamp(b)-stamp(a))}
function badge(ring=false){const list=rows(),n=list.filter(unread).length,b=$(".notification-bell-badge"),bell=$("#notification-inbox-btn");if(!b||!bell)return;b.hidden=!n;b.textContent=n>99?"99+":String(n);bell.setAttribute("aria-label",`Apri Centro notifiche${n?`, ${n} non lette`:""}`);if(ring){bell.classList.remove("is-ringing");requestAnimationFrame(()=>bell.classList.add("is-ringing"));setTimeout(()=>bell.classList.remove("is-ringing"),1600)}}
function when(n){const d=new Date(stamp(n));if(!Number.isFinite(d.getTime()))return"";return d.toDateString()===new Date().toDateString()?d.toLocaleTimeString("it-IT",{hour:"2-digit",minute:"2-digit"}):d.toLocaleDateString("it-IT",{day:"2-digit",month:"short"})}
function detail(n){const fields=[["Operatore",n.actorName],["Commessa",n.commessaName],["Squadra",n.squadraName],["Impianto",n.impiantoName],["Mezzo",n.metadata?.mezzoName]].filter(x=>x[1]);const files=(n.attachments||[]).map((a,i)=>`<button class="btn" data-file="${esc(a.url||"")}">📎 ${esc(a.name||`Allegato ${i+1}`)}</button>`).join("");const ok=n._legacy?`<button class="btn btn-primary" data-confirm="${esc(n._key)}" ${confirmed(n)?"disabled":""}>${confirmed(n)?"✓ CONFERMATA":"OK, HO CAPITO"}</button>`:"";return`<div class="notification-detail"><p>${esc(n.message||n.preview)}</p><p><small>${new Date(stamp(n)).toLocaleString("it-IT")}</small></p>${fields.length?`<dl>${fields.map(x=>`<dt>${esc(x[0])}</dt><dd>${esc(x[1])}</dd>`).join("")}</dl>`:""}${files?`<div class="notification-actions">${files}</div>`:""}${n.actionType||ok?`<div class="notification-actions">${n.actionType?`<button class="btn btn-primary" data-action="${esc(n.actionType)}" data-target="${esc(n.actionTarget||"")}">${esc(n.metadata?.actionLabel||"APRI DETTAGLIO")}</button>`:""}${ok}</div>`:""}<button class="btn notification-trash" data-delete="${esc(n._key)}">🗑️</button></div>`}
function render(){const l=$(".notification-list");if(!l)return;const list=rows().filter(n=>s.filter==="all"||unread(n));l.innerHTML=list.length?list.map(n=>`<div class="notification-row-wrap" role="listitem"><div class="notification-delete-reveal">🗑️ ELIMINA</div><button class="notification-row ${unread(n)?"is-unread":""} ${n.priority==="CRITICA"?"is-critical":""}" data-id="${esc(n._key)}" aria-expanded="${s.expanded===n._key}"><span class="notification-icon">${icon(n)}</span><span class="notification-copy"><span class="notification-row-title">${unread(n)?'<span class="notification-dot"></span>':""}${esc(n.title)}</span><span class="notification-preview">${esc(n.preview||n.message)}</span><span class="notification-meta">${esc([n.actorName,n.commessaName,n.impiantoName].filter(Boolean).join(" • "))}</span>${s.expanded===n._key?detail(n):""}</span><time class="notification-time">${when(n)}</time></button></div>`).join(""):'<p class="notification-empty">Nessuna notifica da mostrare.</p>';swipe()}
function open(){ensureUi();badge();render();const d=$("#notification-center");if(d?.showModal&&!d.open)d.showModal()}function close(){const d=$("#notification-center");if(d?.open)d.close();$("#notification-inbox-btn")?.focus()}
async function patch(n,data){await firebase.firestore().collection(n._collection).doc(n.id).update(data)}
async function read(n){if(!n||!unread(n))return;n.readBy={...(n.readBy||{}),[s.user.uid]:true};badge();render();try{await patch(n,{[`readBy.${s.user.uid}`]:true,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.warn("Lettura notifica non sincronizzata",e)}}
async function confirmLegacy(n){if(!n?._legacy||confirmed(n))return;const d=new Date(),date=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;n.ackByUserIds={...(n.ackByUserIds||{}),[s.user.uid]:true};n.dismissedByUserIds={...(n.dismissedByUserIds||{}),[s.user.uid]:true};n.readBy={...(n.readBy||{}),[s.user.uid]:true};badge();render();try{await Promise.all([firebase.firestore().collection("userAlertAcknowledgements").doc(`${n.id}__${s.user.uid}`).set({notificationId:n.id,userId:s.user.uid,userName:s.user.displayName||s.user.email||"Utente",acknowledgedAt:firebase.firestore.FieldValue.serverTimestamp(),acknowledgedDateKey:date},{merge:true}),patch(n,{[`ackByUserIds.${s.user.uid}`]:firebase.firestore.FieldValue.serverTimestamp(),[`dismissedByUserIds.${s.user.uid}`]:firebase.firestore.FieldValue.serverTimestamp(),[`readBy.${s.user.uid}`]:true,lastAcknowledgedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()})])}catch(e){console.warn("Conferma notifica non sincronizzata",e)}}
async function remove(n){if(!n)return;n.deletedBy={...(n.deletedBy||{}),[s.user.uid]:true};s.items.delete(n._key);s.undo=n;badge();render();try{await patch(n,{[`deletedBy.${s.user.uid}`]:true,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.warn("Eliminazione notifica non sincronizzata",e)}toast()}
function toast(){$(".notification-toast")?.remove();document.body.insertAdjacentHTML("beforeend",'<div class="notification-toast">Notifica eliminata – <button type="button">ANNULLA</button></div>');const t=$(".notification-toast");t.querySelector("button").onclick=undo;setTimeout(()=>t.remove(),5000)}
async function undo(){const n=s.undo;if(!n)return;s.items.set(n._key,n);delete n.deletedBy[s.user.uid];s.undo=null;render();badge();$(".notification-toast")?.remove();try{await patch(n,{[`deletedBy.${s.user.uid}`]:firebase.firestore.FieldValue.delete(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.warn("Ripristino notifica non sincronizzato",e)}}
async function click(e){if(e.target.closest("[data-nc-close]"))return close();const f=e.target.closest("[data-filter]");if(f){s.filter=f.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.setAttribute("aria-selected",String(x===f)));return render()}if(e.target.closest("[data-read-all]")){const list=rows().filter(unread);list.forEach(n=>n.readBy={...(n.readBy||{}),[s.user.uid]:true});badge();render();await Promise.allSettled(list.map(n=>patch(n,{[`readBy.${s.user.uid}`]:true,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})));return}if(e.target.closest("[data-delete-all]")){if(confirm("Eliminare tutte le notifiche?\n\nLe notifiche verranno eliminate solamente dal tuo elenco personale.")){const list=rows();list.forEach(n=>s.items.delete(n._key));badge();render();await Promise.allSettled(list.map(n=>patch(n,{[`deletedBy.${s.user.uid}`]:true,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})))}return}const c=e.target.closest("[data-confirm]");if(c)return confirmLegacy(s.items.get(c.dataset.confirm));const file=e.target.closest("[data-file]");if(file){if(file.dataset.file)window.open(file.dataset.file,"_blank","noopener,noreferrer");return}const del=e.target.closest("[data-delete]");if(del)return remove(s.items.get(del.dataset.delete));const action=e.target.closest("[data-action]");if(action){dispatchEvent(new CustomEvent("hera:open-notification-destination",{detail:{destination:action.dataset.action,target:action.dataset.target}}));return close()}const row=e.target.closest("[data-id]");if(row){const n=s.items.get(row.dataset.id);if(!n)return;s.expanded=s.expanded===n._key?"":n._key;await read(n);render()}}
function swipe(){document.querySelectorAll(".notification-row").forEach(row=>{row.onpointerdown=e=>{if(e.pointerType!=="mouse")s.touch={row,x:e.clientX,y:e.clientY}};row.onpointermove=e=>{const t=s.touch;if(!t||t.row!==row)return;const dx=Math.min(0,e.clientX-t.x);if(Math.abs(dx)>Math.abs(e.clientY-t.y))row.style.transform=`translateX(${Math.max(-120,dx)}px)`};row.onpointerup=e=>{const t=s.touch;s.touch=null;if(!t)return;e.clientX-t.x<-80?remove(s.items.get(row.dataset.id)):row.style.transform=""}})}
function snapshot(tag,snap,normalizer){const next=new Set(),initial=s.ready.has(tag);let fresh=false;snap.docs.forEach(d=>{const n=normalizer(d.id,d.data());if(!visible(n))return;next.add(n._key);if(initial&&!s.seen.has(n._key))fresh=true;s.seen.add(n._key);s.items.set(n._key,n)});const prev=s.sources.get(tag)||new Set();for(const k of prev)if(!next.has(k)&&![...s.sources.entries()].some(([t,keys])=>t!==tag&&keys.has(k)))s.items.delete(k);s.sources.set(tag,next);s.ready.add(tag);badge(fresh);render()}
function listen(tag,q,norm){let fallbackTimer=null,stopped=false;const load=async()=>{if(stopped||!s.user)return;try{const x=await q.get();if(!stopped)snapshot(tag,x,norm)}catch(e){console.warn(`Recupero Centro notifiche (${tag})`,e)}};const unsubscribe=q.onSnapshot(x=>snapshot(tag,x,norm),e=>{console.warn(`Listener Centro notifiche (${tag})`,e);load();if(!fallbackTimer)fallbackTimer=setInterval(load,60000)});s.unsubs.push(()=>{stopped=true;unsubscribe?.();if(fallbackTimer)clearInterval(fallbackTimer)})}
function stop(){s.unsubs.splice(0).forEach(x=>x?.());s.items.clear();s.sources.clear();s.ready.clear();s.seen.clear();s.user=null;s.expanded="";badge();render()}
function subscribe(user){stop();s.user=user;if(!user)return;const db=firebase.firestore();if(admin())listen("central-admin",db.collection(C).limit(500),central);else{listen("central-global",db.collection(C).where("scopeType","==","GLOBALE").limit(500),central);listen("central-personal",db.collection(C).where("recipientUserIds","array-contains",user.uid).limit(500),central)}listen("legacy-user-alerts",db.collection(L).limit(500),legacy)}
function queue(p){const a=JSON.parse(localStorage.getItem(Q)||"[]");if(!a.some(x=>x.dedupeKey===p.dedupeKey))a.push(p);localStorage.setItem(Q,JSON.stringify(a))}
async function create(payload){const p={...payload,dedupeKey:payload.dedupeKey||`${payload.type}:${Date.now()}`};try{if(!navigator.onLine)throw Error("offline");const fn=firebase.app?.().functions?.("europe-west1")?.httpsCallable?.("createCentralNotification")||firebase.functions?.().httpsCallable?.("createCentralNotification");if(!fn)throw Error("functions unavailable");await fn(p);return true}catch(e){queue(p);console.warn("Notifica accodata senza bloccare l’azione principale",e);return false}}
async function flush(){if(!s.user||!navigator.onLine)return;const a=JSON.parse(localStorage.getItem(Q)||"[]"),pending=[];for(const p of a)if(!(await create(p)))pending.push(p);localStorage.setItem(Q,JSON.stringify(pending))}
function start(){ensureUi();if(!window.firebase?.auth)return;firebase.auth().onAuthStateChanged(subscribe);addEventListener("online",flush);addEventListener("visibilitychange",()=>{if(!document.hidden){flush();if(s.user)subscribe(s.user)}})}
window.HeraNotificationCenter={create,open,flush};document.readyState==="loading"?addEventListener("DOMContentLoaded",start,{once:true}):start();
})();