(function installNotificationCenter(){
  "use strict";
  const COLLECTION="notifications", QUEUE_KEY="hera_notification_outbox_v1";
  const state={user:null,items:new Map(),unsubs:[],filter:"all",expanded:"",initial:true,lastIds:new Set(),undo:null,touch:null};
  const $=(s,r=document)=>r.querySelector(s);
  const timestamp=n=>{const v=n?.createdAt;return v?.toMillis?.()||v?.toDate?.().getTime?.()||Date.parse(v||0)||0};
  const unread=n=>Boolean(state.user&&!n.readBy?.[state.user.uid]);
  const isAdmin=()=>Boolean(state.user?.email&&/^(ionut29019)@gmail\.com$/i.test(state.user.email));
  const visible=n=>isAdmin()||n.scopeType==="GLOBALE"||(n.recipientUserIds||[]).includes(state.user?.uid);
  const icon=n=>({WORKLIMATE:"🔴",METEO:"⚠️",IMPIANTO_COMPLETATO:"✅",NAVIGAZIONE:"📍",ORE:"🕒",SQUADRA:"👥",MEZZO:"🚚",SYNC_ERROR:"⛔"}[n.type]||"🔔");
  function ensureUi(){
    let bell=$("#notification-inbox-btn");
    if(!bell){bell=document.createElement("button");bell.id="notification-inbox-btn";bell.type="button";bell.className="header-icon-btn notification-bell";bell.innerHTML='<span aria-hidden="true">🔔</span><span class="notification-bell-badge" hidden></span>';$(".logo-head-action-icons")?.prepend(bell)}
    else{bell.classList.add("notification-bell");bell.innerHTML='<span aria-hidden="true">🔔</span><span class="notification-bell-badge" hidden></span>'}
    bell.title="Centro notifiche";bell.setAttribute("aria-label","Apri Centro notifiche");bell.addEventListener("click",open);
    if(!$("#notification-center")){document.body.insertAdjacentHTML("beforeend",`<dialog id="notification-center" class="notification-center" aria-labelledby="notification-center-title"><div class="notification-center-shell"><header class="notification-center-head"><div class="notification-center-title-row"><h2 id="notification-center-title">Notifiche</h2><button class="btn" data-nc-close aria-label="Chiudi Centro notifiche">✕</button></div><div class="notification-filter" role="tablist" aria-label="Filtra notifiche"><button class="btn" data-filter="all" role="tab" aria-selected="true">TUTTE</button><button class="btn" data-filter="unread" role="tab" aria-selected="false">NON LETTE</button></div></header><div class="notification-list" role="list"></div><footer class="notification-center-foot"><button class="btn" data-read-all>SEGNA TUTTE COME LETTE</button><button class="btn danger" data-delete-all>ELIMINA TUTTE LE NOTIFICHE</button><button class="btn" data-nc-close>CHIUDI</button></footer></div></dialog>`)}
    bindUi();return bell;
  }
  function bindUi(){const d=$("#notification-center");if(d.dataset.bound)return;d.dataset.bound="1";d.addEventListener("click",onClick);d.addEventListener("keydown",e=>{if(e.key==="Escape")close()});}
  function ordered(){return [...state.items.values()].filter(visible).sort((a,b)=>((unread(b)&&b.priority==="CRITICA")-(unread(a)&&a.priority==="CRITICA"))||timestamp(b)-timestamp(a));}
  function updateBadge(animate=false){const rows=ordered(),count=rows.filter(unread).length,badge=$(".notification-bell-badge"),bell=$("#notification-inbox-btn");badge.hidden=count===0;badge.textContent=count>99?"99+":String(count);bell.setAttribute("aria-label",`Apri Centro notifiche${count?`, ${count} non lette`:""}`);if(animate){bell.classList.remove("is-ringing");requestAnimationFrame(()=>bell.classList.add("is-ringing"));setTimeout(()=>bell.classList.remove("is-ringing"),1600)}}
  function formatWhen(n){const d=new Date(timestamp(n));if(!Number.isFinite(d.getTime()))return "";const now=new Date();return d.toDateString()===now.toDateString()?d.toLocaleTimeString("it-IT",{hour:"2-digit",minute:"2-digit"}):d.toLocaleDateString("it-IT",{day:"2-digit",month:"short"})}
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  function detail(n){const fields=[["Operatore",n.actorName],["Commessa",n.commessaName],["Squadra",n.squadraName],["Impianto",n.impiantoName],["Mezzo",n.metadata?.mezzoName],["Stato precedente",n.metadata?.previousState],["Nuovo stato",n.metadata?.newState],["Meteo",n.metadata?.weather],["Worklimate",n.metadata?.worklimate],["Indicazioni",n.metadata?.instructions]].filter(x=>x[1]);return `<div class="notification-detail"><p>${esc(n.message||n.preview)}</p><p><small>${new Date(timestamp(n)).toLocaleString("it-IT")}</small></p>${fields.length?`<dl>${fields.map(x=>`<dt>${esc(x[0])}</dt><dd>${esc(x[1])}</dd>`).join("")}</dl>`:""}${n.actionType?`<div class="notification-actions"><button class="btn btn-primary" data-action="${esc(n.actionType)}" data-target="${esc(n.actionTarget||"")}">${esc(n.metadata?.actionLabel||"APRI DETTAGLIO")}</button></div>`:""}<button class="btn notification-trash" data-delete="${esc(n.id)}" aria-label="Elimina notifica">🗑️</button></div>`}
  function render(){const list=$(".notification-list");if(!list)return;const rows=ordered().filter(n=>state.filter==="all"||unread(n));list.innerHTML=rows.length?rows.map(n=>`<div class="notification-row-wrap" role="listitem" data-wrap="${esc(n.id)}"><div class="notification-delete-reveal" aria-hidden="true">🗑️ ELIMINA</div><button class="notification-row ${unread(n)?"is-unread":""} ${n.priority==="CRITICA"?"is-critical":""}" data-id="${esc(n.id)}" aria-expanded="${state.expanded===n.id}" aria-label="${unread(n)?"Non letta: ":""}${esc(n.title)}"><span class="notification-icon" aria-hidden="true">${icon(n)}</span><span class="notification-copy"><span class="notification-row-title">${unread(n)?'<span class="notification-dot" aria-hidden="true"></span>':""}${esc(n.title)}</span><span class="notification-preview">${esc(n.preview||n.message)}</span><span class="notification-meta">${esc([n.actorName,n.commessaName,n.impiantoName].filter(Boolean).join(" • "))}</span>${state.expanded===n.id?detail(n):""}</span><time class="notification-time">${formatWhen(n)}</time></button></div>`).join(""):'<p class="notification-empty">Nessuna notifica da mostrare.</p>';installSwipe()}
  function open(){const d=$("#notification-center");render();if(d.showModal&&!d.open)d.showModal();setTimeout(()=>$("[data-nc-close]",d)?.focus(),0)}function close(){const d=$("#notification-center");if(d?.open)d.close();$("#notification-inbox-btn")?.focus()}
  async function patch(id,data){const ref=firebase.firestore().collection(COLLECTION).doc(id);await ref.update(data)}
  async function markRead(n){if(!unread(n))return;n.readBy={...(n.readBy||{}),[state.user.uid]:true};updateBadge();render();try{await patch(n.id,{[`readBy.${state.user.uid}`]:true,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.warn("Lettura notifica non sincronizzata",e)}}
  async function remove(n){n.deletedBy={...(n.deletedBy||{}),[state.user.uid]:true};state.items.delete(n.id);state.undo=n;updateBadge();render();try{await patch(n.id,{[`deletedBy.${state.user.uid}`]:true,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.warn("Eliminazione notifica non sincronizzata",e)}toast()}
  function toast(){let t=$(".notification-toast");t?.remove();document.body.insertAdjacentHTML("beforeend",'<div class="notification-toast" role="status">Notifica eliminata – <button type="button">ANNULLA</button></div>');t=$(".notification-toast");t.querySelector("button").onclick=undo;setTimeout(()=>t.remove(),5000)}
  async function undo(){const n=state.undo;if(!n)return;state.items.set(n.id,n);delete n.deletedBy[state.user.uid];state.undo=null;render();updateBadge();$(".notification-toast")?.remove();try{await patch(n.id,{[`deletedBy.${state.user.uid}`]:firebase.firestore.FieldValue.delete()})}catch(e){console.warn("Ripristino notifica non sincronizzato",e)}}
  async function onClick(e){if(e.target.closest("[data-nc-close]"))return close();const f=e.target.closest("[data-filter]");if(f){state.filter=f.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.setAttribute("aria-selected",String(x===f)));return render()}if(e.target.closest("[data-read-all]")){const rows=ordered().filter(unread);rows.forEach(n=>n.readBy={...(n.readBy||{}),[state.user.uid]:true});updateBadge();render();await Promise.allSettled(rows.map(n=>patch(n.id,{[`readBy.${state.user.uid}`]:true})));return}if(e.target.closest("[data-delete-all]")){if(confirm("Eliminare tutte le notifiche?\n\nLe notifiche verranno eliminate solamente dal tuo elenco personale.")){const rows=ordered();state.items.clear();updateBadge();render();await Promise.allSettled(rows.map(n=>patch(n.id,{[`deletedBy.${state.user.uid}`]:true}))) }return}const del=e.target.closest("[data-delete]");if(del)return remove(state.items.get(del.dataset.delete));const action=e.target.closest("[data-action]");if(action){window.dispatchEvent(new CustomEvent("hera:open-notification-destination",{detail:{destination:action.dataset.action,target:action.dataset.target}}));close();return}const row=e.target.closest("[data-id]");if(row){const n=state.items.get(row.dataset.id);state.expanded=state.expanded===n.id?"":n.id;await markRead(n);render()}}
  function installSwipe(){document.querySelectorAll(".notification-row").forEach(row=>{row.addEventListener("pointerdown",e=>{if(e.pointerType==="mouse")return;state.touch={row,x:e.clientX,y:e.clientY}});row.addEventListener("pointermove",e=>{const t=state.touch;if(!t||t.row!==row)return;const dx=Math.min(0,e.clientX-t.x);if(Math.abs(dx)>Math.abs(e.clientY-t.y))row.style.transform=`translateX(${Math.max(-120,dx)}px)`});row.addEventListener("pointerup",e=>{const t=state.touch;state.touch=null;if(!t)return;if(e.clientX-t.x < -80)remove(state.items.get(row.dataset.id));else row.style.transform=""})})}
  function stop(){state.unsubs.splice(0).forEach(fn=>fn?.());state.items.clear();state.user=null;state.initial=true;updateBadge();render()}
  function subscribe(user){stop();state.user=user;if(!user)return;const db=firebase.firestore(),queries=isAdmin()?[db.collection(COLLECTION).orderBy("createdAt","desc").limit(500)]:[db.collection(COLLECTION).where("scopeType","==","GLOBALE").limit(500),db.collection(COLLECTION).where("recipientUserIds","array-contains",user.uid).limit(500)];queries.forEach(q=>state.unsubs.push(q.onSnapshot(s=>{let fresh=false;s.docChanges().forEach(c=>{const n={id:c.doc.id,...c.doc.data()};if(c.type==="removed"||n.deletedBy?.[user.uid])state.items.delete(n.id);else{fresh=fresh||(!state.initial&&c.type==="added"&&!state.lastIds.has(n.id));state.items.set(n.id,n);state.lastIds.add(n.id)}});updateBadge(fresh);render();state.initial=false},e=>console.warn("Listener Centro notifiche",e))))}
  function queue(payload){const rows=JSON.parse(localStorage.getItem(QUEUE_KEY)||"[]");if(!rows.some(x=>x.dedupeKey===payload.dedupeKey))rows.push(payload);localStorage.setItem(QUEUE_KEY,JSON.stringify(rows))}
  async function create(payload){const p={...payload,dedupeKey:payload.dedupeKey||`${payload.type}:${Date.now()}`};try{if(!navigator.onLine)throw new Error("offline");const callable=firebase.app?.().functions?.("europe-west1")?.httpsCallable?.("createCentralNotification") || firebase.functions?.().httpsCallable?.("createCentralNotification");if(!callable)throw new Error("functions unavailable");await callable(p);return true}catch(e){queue(p);console.warn("Notifica accodata senza bloccare l’azione principale",e);return false}}
  async function flush(){if(!state.user||!navigator.onLine)return;const rows=JSON.parse(localStorage.getItem(QUEUE_KEY)||"[]"),pending=[];for(const p of rows)if(!(await create(p)))pending.push(p);localStorage.setItem(QUEUE_KEY,JSON.stringify(pending))}
  function start(){ensureUi();if(!window.firebase?.auth)return;firebase.auth().onAuthStateChanged(subscribe);addEventListener("online",flush);document.addEventListener("visibilitychange",()=>{if(!document.hidden)flush()})}
  window.HeraNotificationCenter={create,open,flush};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();
